### ISSUE TITLE
Face detection & cropping method

### ISSUE THREAD

**Issue by clementabary** [neuralchen/SimSwap#11]
Hi, great work !

I am trying on my own images, and the result changes a lot depending on the cropping conditions of the face. What backend are you using to align your faces ? I use `face-alignment` to detect the face, crop the face centered on the nose and rotated along the axis `eye_average->mouth`. Still I don't know the extent of the cropping. Can you help me with that ?

Thanks a lot in advance !

**Comment by NNNNAI** [comment]
Thank you for your concern about our work. I currently use the face detection and face alignment methods from [InsightFace](https://github.com/deepinsight/insightface). You can refer to their specific implementation of alignment. Then can you release the picture after you crop it now? This will allow me to better understand your problem and solve it. We will open source the code for changing faces on any picture as soon as possible in the next few days.

**Comment by NNNNAI** [comment]
Thank you for your concern about our work. I currently use the face detection and face alignment methods from [InsightFace](https://github.com/deepinsight/insightface). You can refer to their specific implementation of alignment. Then can you show me the picture after your crop? This will allow me to better understand your problem and solve it. We will open source the code for changing faces on any picture as soon as possible in the next few days.

**Comment by clementabary** [comment]
My cropping was a bit zoomed out so the result was not as good as with your alignment methodology, thanks again !
