### ISSUE TITLE
Improvement Model

### ISSUE THREAD

**Issue by aestheticart** [neuralchen/SimSwap#115]
This is great project. Thanks for developer. But now I think we need focus on Training Model. All progress on colab normaly on video swap, image on docker. But i think we need something for better improvement.

1. Manual setting on Colab or CLI about setting 224 crop or something. Because i got blurry.
2. Training model for better face similarity.
3. Improved face swap when the face is facing the right or left side. Then when facing up or down is not detected.
4. Result Enchance Face HD

Thank you, great project developer. This project can be better than DFL because its faster result.

**Comment by neuralchen** [comment]
Thanks for your excellent suggestion.
The most efficient way to improve the output quality is to collect a high quality dataset.
