### ISSUE TITLE
onnxruntime error every time

### ISSUE THREAD

**Issue by chud37** [neuralchen/SimSwap#117]
This is what i get:

```
2021-09-15 05:36:01.6647118 [E:onnxruntime:Default, provider_bridge_ort.cc:952 onnxruntime::ProviderLibrary::Get] Failed to load library, error code: 126
2021-09-15 05:36:02.3730950 [E:onnxruntime:Default, provider_bridge_ort.cc:952 onnxruntime::ProviderLibrary::Get] Failed to load library, error code: 126
```

Does that mean my graphics card isnt working?  How to fix this?

**Comment by chenr1** [comment]
https://www.youtube.com/watch?v=Tiq_vea5Eqg
Do the things described in this video. You'll need to download Cuda and then add the cudaNN libraries to your cuda installation.

**Comment by chud37** [comment]
Hi, Thanks yes I did the things exactly as described in the video, however I'm still getting the error.  What else can i do to fix this? It's failing to to load the library, but I can't see why.  


This was the response I got when I last ran the install commands:
```
(simswap) c:\simswap>pip install onnxruntime
Requirement already satisfied: onnxruntime in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (1.8.1)
Requirement already satisfied: numpy>=1.16.6 in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime) (1.19.5)
Requirement already satisfied: protobuf in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime) (3.18.0)
Requirement already satisfied: flatbuffers in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime) (2.0)

(simswap) c:\simswap>pip install onnxruntime-gpu
Requirement already satisfied: onnxruntime-gpu in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (1.8.1)
Requirement already satisfied: flatbuffers in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime-gpu) (2.0)
Requirement already satisfied: numpy>=1.16.6 in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime-gpu) (1.19.5)
Requirement already satisfied: protobuf in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime-gpu) (3.18.0)
```

Which would seem to suggest everything is okay?  So why am I still getting the failed to load library errors?

**Comment by NNNNAI** [comment]
Try to uninstall onnxruntime-gpu，just install onnxruntime.

**Comment by chenr1** [comment]
> 
> 
> Hi, Thanks yes I did the things exactly as described in the video, however I'm still getting the error. What else can i do to fix this? It's failing to to load the library, but I can't see why.
> 
> This was the response I got when I last ran the install commands:
> 
> ```
> (simswap) c:\simswap>pip install onnxruntime
> Requirement already satisfied: onnxruntime in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (1.8.1)
> Requirement already satisfied: numpy>=1.16.6 in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime) (1.19.5)
> Requirement already satisfied: protobuf in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime) (3.18.0)
> Requirement already satisfied: flatbuffers in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime) (2.0)
> 
> (simswap) c:\simswap>pip install onnxruntime-gpu
> Requirement already satisfied: onnxruntime-gpu in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (1.8.1)
> Requirement already satisfied: flatbuffers in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime-gpu) (2.0)
> Requirement already satisfied: numpy>=1.16.6 in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime-gpu) (1.19.5)
> Requirement already satisfied: protobuf in c:\users\chud3\anaconda3\envs\simswap\lib\site-packages (from onnxruntime-gpu) (3.18.0)
> ```
> 
> Which would seem to suggest everything is okay? So why am I still getting the failed to load library errors?

You sure you did everything else correct? Is there error different? This may be dumb but did you restart your console window? 
The error you sent means that the cudaNN isn't present. If you added the files exactly as described in the video the error will cease.

**Comment by chud37** [comment]
> You sure you did everything else correct? Is there error different? This may be dumb but did you restart your console window?
> The error you sent means that the cudaNN isn't present. If you added the files exactly as described in the video the error will cease.

Yeah I downloaded CudaNN just like the video said and transfered the correct files to the correct directory.  I will try it again.  Thank you for explaining what the error meant, it helps a lot.  I'll update once I've given it another try.

**Comment by chud37** [comment]
Hey, just to say that yeah I think I hadn't restarted the anaconda prompt and today its working no errors- I'm not getting 6-11it/s instead of the usual 3-4it/s.  THank you!
