### ISSUE TITLE
missing file 77779_iter.pth

### ISSUE THREAD

**Issue by evergreentrance** [neuralchen/SimSwap#126]
Apologies for the inconvenience but I stumbled across this error:

FileNotFoundError: [Errno 2] No such file or directory: './parsing_model/checkpoint\\79999_iter.pth'

I'm a complete newbie when it comes to code, but I was trying to set this up and this appeared on my first attempt at swapping.

I set it up mainly using this tutorial: https://www.youtube.com/watch?v=1NWJz_rFMq0 (It *is* from June if that makes it outdated enough to cause this.)

If this has a fix, please let me know when you can; this software seems super cool!

- evergreen

**Comment by ssbugman** [comment]
Why you not said how you fixed this? It still missing.
