### ISSUE TITLE
Can this be used on Windows 8.1 x64?

### ISSUE THREAD

**Issue by paulescobar** [neuralchen/SimSwap#128]
When I ran a test job on a Windows 8.1 x64 PC, it gave me a message at the start of the job that said...
`UserWarning: Unsupported Windows version (8.1). ONNX Runtime supports Windows 10 and above, only.`

Then it progressed, but ended with this error message
```
FileNotFoundError: [Errno 2] No such file or directory: './parsing_model/checkpo
int\\79999_iter.pth'
```
Should I upgrade my operating system to use this?
Or is there a way to use this with Windows 8.1?

**Comment by instant-high** [comment]
Second error has nothing to do with your windows version. Missing file for soft mask.
Nevertheless I don't know if it runs on win8.
I guess not

**Comment by paulescobar** [comment]
> Second error has nothing to do with your windows version. Missing file for soft mask. Nevertheless I don't know if it runs on win8. I guess not

I downloaded the code as zip.
The file "79999_iter.pth" wasn't included.
Where can I find it?
What path do I place it?
