### ISSUE TITLE
When will SimSwapLive be released?

### ISSUE THREAD

**Issue by block-sexy** [neuralchen/SimSwap#137]
Looking forward to it, thank you！

**Comment by block-sexy** [comment]
> Did you mean real time simswap version?

Yes, change faces in real time;

**Comment by block-sexy** [comment]
In addition, there is still a lot of room for improvement. Many video results are not perfect.

**Comment by block-sexy** [comment]
> Did you mean real time simswap version?

like https://github.com/iperov/DeepFaceLive

**Comment by NNNNAI** [comment]
We currently have no plans to make the live version.

**Comment by Ilyaprok** [comment]
> We currently have no plans to make the live version.

Thnak you very much for this project! is it difficult to make this program real-time? Maybe you tell me which way to move? Maybe in DeepFaceLive I need replace some elements with your project?

**Comment by NNNNAI** [comment]
> > We currently have no plans to make the live version.
> 
> Thank you very much for this project! is it difficult to make this program real-time? Maybe you tell me which way to move? Maybe in DeepFaceLive I need replace some elements with your project?

The "reverse2wholeimage" function  in [reverse2original.py](https://github.com/neuralchen/SimSwap/blob/main/util/reverse2original.py) is time-consuming,you can try to optimize it.

**Comment by block-sexy** [comment]
> > > We currently have no plans to make the live version.
> > 
> > 
> > Thank you very much for this project! is it difficult to make this program real-time? Maybe you tell me which way to move? Maybe in DeepFaceLive I need replace some elements with your project?
> 
> The "reverse2wholeimage" function in [reverse2original.py](https://github.com/neuralchen/SimSwap/blob/main/util/reverse2original.py) is time-consuming,you can try to optimize it.

thank you very much

**Comment by giorgiop** [comment]
@tangwenru https://github.com/sensity-ai/dot
