### ISSUE TITLE
THRESHOLD ERROR

### ISSUE THREAD

**Issue by seonake** [neuralchen/SimSwap#139]
Hi, i am geting this error.
Anyone knows how to fix it?
Many thanks in advance

Traceback (most recent call last):
  File "test_video_swapspecific.py", line 50, in <module>
    img_a_align_crop, _ = app.get(img_a_whole,crop_size)
  File "H:\faceswap\insightface_func\face_detect_crop_multi.py", line 55, in get
    bboxes, kpss = self.det_model.detect(img,
TypeError: detect() got an unexpected keyword argument 'threshold'

**Comment by NNNNAI** [comment]
The version of your insightface is too high. Try to uninstall to insightface and use pip install insightface==0.2.1 to reinstall it ,

**Comment by seonake** [comment]
OK. Many thanks

**Comment by NNNNAI** [comment]
Have  a nice day.

**Comment by woctezuma** [comment]
For info, there is an issue with version 0.2.1 now.

**Comment by woctezuma** [comment]
Related:
- #407 

I can fix this with:
- https://github.com/neuralchen/SimSwap/pull/447
