### ISSUE TITLE
Great God, when will cudatoolkit 11 be supported?

### ISSUE THREAD

**Issue by block-sexy** [neuralchen/SimSwap#144]
The current version only supports cudatoolkit 10!
NVIDIA 30 series graphics cards are all cudatoolkit 11! So NVIDIA 30 series graphics cards cannot use SimSwap!

Guiqiu God support, there are not many functions that need to be modified, mainly the upgrade support of some functions such as .set_device / .device()

**Comment by bmc84** [comment]
You need to be blocked: your spam of the Issues is _really_ irritating.

You also clearly don't know what you are doing: I am using a 30xx graphics card, which works incredibly well with SimSwap.

Please stop creating new issues which aren't real issues.
