### ISSUE TITLE
it does not work under Nvidia RTX3090

### ISSUE THREAD

**Issue by oracle9i88** [neuralchen/SimSwap#15]

**Comment by NNNNAI** [comment]
Can you describe in detail how it doesn't work. For example, bug reports and the like.

**Comment by oracle9i88** [comment]
C:\ProgramData\Miniconda3\envs\simswap\lib\site-packages\torch\cuda\__init__.py:104: UserWarning:
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))

**Comment by oracle9i88** [comment]
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch

just try

**Comment by dodo295** [comment]
pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html

Try it

**Comment by oracle9i88** [comment]
> pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
> 
> pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html
> 
> Try it

pip install error，wuwu

**Comment by dodo295** [comment]
> > pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
> > pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html
> > Try it
> 
> pip install error，wuwu

> > Try to create a virtual environment and then apply these two lines again.

**Comment by oracle9i88** [comment]
IValueError: check_hostname requires server_hostname
I'v finished the virtual environment...

**Comment by oracle9i88** [comment]
> > > pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
> > > pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html
> > > Try it
> > 
> > 
> > pip install error，wuwu
> 
> > > Try to create a virtual environment and then apply these two lines again.

thanks, I'v slove it

**Comment by AK391** [comment]
@NNNNAI can inference be done on cpu?

**Comment by NNNNAI** [comment]
Theoretically, it can be inference on the cpu. But inference time will be much longer than on gpu. So I recommend you to use [colab](https://colab.research.google.com/github/neuralchen/SimSwap/blob/main/SimSwap%20colab.ipynb) instead of your own cpu
