### ISSUE TITLE
(not issue) Question to the authors

### ISSUE THREAD

**Issue by netrunner-exe** [neuralchen/SimSwap#151]
Hi! First of all I would like to thank the authors for this wonderful repo!  I understand that you are already tired of questions about the date of releasing training code, but still I would like to ask - is the releasing of the training planned? We have been waiting for this for many months and we still hope for that. Unfortunately, some repository (i will don't post a link but i think all knows about this repo) has appeared with non-working code for training and many people are trying to get the result and wasting time. I would like to try to train the model with working official code, if you really plan to release it. I hope for feedback, very big thanks for everything that you are doing for the whole community!

**Comment by nonlin** [comment]
I also wonder if it is hesitation? Pride? Research restrictions? Or what? The code should exist already so I'm not sure why they delay. 
They have their license which states for non-commericial use, that isn't enough? 

Not trying to stir the pot but I genuinely don't understand why the delay with training code.
