### ISSUE TITLE
How to use VGGFace2-HQ with SimSwap? (Not an "issue")

### ISSUE THREAD

**Issue by bmc84** [neuralchen/SimSwap#155]
Hi,

Does anybody have any idea or steps or code for how to incorporate the authors new repo VGGFace2-HQ (https://github.com/NNNNAI/VGGFace2-HQ ) into SimSwap?

I am not smart enough to do this, but it is clearly possible.

Any information would be very helpful! 

Thank you in advance.

**Comment by netrunner-exe** [comment]
This will be possible when the developers **release the training code** for SimSwap. Then it will be possible to train your own model for SimSwap with this dataset. So far, unfortunately, while the developers do not release the training code for SimSwap, I see no practical use of VGGFace2-HQ in the context of SimSwap.

**Comment by bmc84** [comment]
> This will be possible when the developers **release the training code** for SimSwap. Then it will be possible to train your own model for SimSwap with this dataset. So far, unfortunately, while the developers do not release the training code for SimSwap, I see no practical use of VGGFace2-HQ in the context of SimSwap.

I don't think training is necessary.

I think VGGFace2-HQ could be incorporated into SimSwap:
Currently, my understanding, is that SimSwap performs face extraction (using Insightface), then it performs the face swap.
VGGFace2-HQ has two steps: 1) extract / align (using Insightface), 2) upscale face (using GFPGAN).

Someone who understands these repos more than me could surely just add VGG into the mix:
SimSwap (performs face extraction).
VGGFace2-HQ performs the upscale (using GFPFAN)
SimSwap performs the face swap using the upscaled face.

OR: SimSwap extracts face, swaps face, then re-extract the face, and VGG GFPGAN upscales it.

Either way, you don't need training from scratch.

**Comment by uubuge** [comment]
这怎么用啊，顺便说一下运行环境啊，我调试好的，运行提示页面缓存不够，是显存不足吧

**Comment by neuralchen** [comment]
Training scripts are available now!
