### ISSUE TITLE
Will 512 version be updated soon? - "not an issue but an information"

### ISSUE THREAD

**Issue by osushilover** [neuralchen/SimSwap#165]
### First of all, I appreciate all contributor's help.
Because of you guys, I've tried _**SimSwap-HQ**_ on Colab.
However, it is insufficient at present in face detection and merging.
If anyone has a good way to improve the quality, please let me know.

FYI,
These are several results of Simswap 512 (beta version) on me.

## LQ(L) / HQ(R) Comparison
<div>
<img width=49% src="https://raw.githubusercontent.com/osushilover/comparison_f_ss/main/old/001.jpg"/>
<img width=49% src="https://raw.githubusercontent.com/osushilover/comparison_f_ss/main/new/001.jpg"/>
</div>
<div>
<img width=49% src="https://raw.githubusercontent.com/osushilover/comparison_f_ss/main/old/009.jpg"/>
<img width=49% src="https://raw.githubusercontent.com/osushilover/comparison_f_ss/main/new/009.jpg"/>
</div>
<div>
<img width=49% src="https://raw.githubusercontent.com/osushilover/comparison_f_ss/main/old/019.jpg"/>
<img width=49% src="https://raw.githubusercontent.com/osushilover/comparison_f_ss/main/new/019.jpg"/>
</div>

**Comment by NNNNAI** [comment]
Sure , the released Simswap 512 is still a beta version. We will collect the feedback and try to improve it.

**Comment by Zhangxinnian** [comment]
Hello, for this kind of large-angle side face, face change effect is not good, do you have any ideas for optimization.Looking forward to your reply. @NNNNAI

**Comment by NNNNAI** [comment]
> Hello, for this kind of large-angle side face, face change effect is not good, do you have any ideas for optimization.Looking forward to your reply. @NNNNAI

Sorry, this may casued by the training data lack of such a large-angle side face.

**Comment by Zhangxinnian** [comment]
> > 您好，对于这种大角度侧脸，换脸效果不好，您有什么优化的想法，期待您的回复。@NNNNAI
> 
> 抱歉，这可能是由于训练数据缺乏如此大角度的侧面造成的。

Okay, I will try to complete the data, retrain and optimize, and submit a new issue if it works.thanks.

**Comment by Zhangxinnian** [comment]
> > Hello, for this kind of large-angle side face, face change effect is not good, do you have any ideas for optimization.Looking forward to your reply. @NNNNAI
> 
> Sorry, this may casued by the training data lack of such a large-angle side face.

Okay, I will try to complete the data, retrain and optimize, and submit a new issue if it works.thanks.

**Comment by ramnnv** [comment]
For now i still prefer the LQ version, but i'm patient and appreciated the effort of the team. ♥

**Comment by lhucklen** [comment]
I am getting similar results as above. Best of luck as you develop this. I am sure it is not an easy undertaking.

**Comment by osushilover** [comment]
> 確かに、リリースされたSimswap512はまだベータ版です。フィードバックを収集し、改善に努めます。

I'm honored hear you say that.
Love,
