### ISSUE TITLE
Simswap HQ checkpoint/pretrained model

### ISSUE THREAD

**Issue by Echolink50** [neuralchen/SimSwap#175]
Sorry for the basic question but do I need all the files on the google drive?

https://drive.google.com/drive/folders/1ZHy7jrd6cGb2lUa4qYugXe41G_Ef9Ibw

Its like 100GB. Do I just need the zip? Its 9GB. I can't even see whats in it without downloading.  Thanks for the help

**Comment by nonlin** [comment]
I think that is if you want to do training yourself which hasn't been released yet. 
You should be able to get by with the checkpoints. https://drive.google.com/drive/folders/1jV6_0FIMPC53FZ2HzZNJZGMe55bbu17R

**Comment by Echolink50** [comment]
Ok thanks. Was Simswap 512 trained on VGGFace2-HQ? It's confusing but I was thinking Simswap HQ and 512 were different. Thanks again

**Comment by nonlin** [comment]
They state this "We trained a beta version of Simswap 512 on VGGFace2-HQ and open sourced the model (if you think the Simswap 512 is cool, please star our VGGFace2-HQ repo)."
