### ISSUE TITLE
Is aligned version of VGGFace2 dataset (not HQ) available?

### ISSUE THREAD

**Issue by mzp0514** [neuralchen/SimSwap#177]
Hi! I saw that you published the HQ version of VGGFace2, which is with size 512 * 512. I wonder if you can provide the aligned dataset with size 224 * 224? Thank you!

**Comment by yymango** [comment]
Have you gotten the 224*224 dataset？Could you please share with me？Thanks! my emali:   yuanyin_1016@163.com
