### ISSUE TITLE
AssertionError line 47

### ISSUE THREAD

**Issue by alexhuber123** [neuralchen/SimSwap#187]
What am I doing wrong? i see other Assertion Errors that have been solved and followed directions but i still cant figure this out.

(simswap) C:\Users\User\Desktop\SimSwap-main>python test_video_swapsingle.py --crop_size 224 --use_mask --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path ./demo_file/Iron_man.jpg --video_path ./demo_file/video1.mp4 --output_path ./output/test.mp4 --temp_path ./temp_results
------------ Options -------------
Arc_path: arcface_model/arcface_checkpoint.tar
aspect_ratio: 1.0
batchSize: 8
checkpoints_dir: ./checkpoints
cluster_path: features_clustered_010.npy
crop_size: 224
data_type: 32
dataroot: ./datasets/cityscapes/
display_winsize: 512
engine: None
export_onnx: None
feat_num: 3
fineSize: 512
fp16: False
gpu_ids: [0]
how_many: 50
id_thres: 0.03
image_size: 224
input_nc: 3
instance_feat: False
isTrain: False
label_feat: False
label_nc: 0
latent_size: 512
loadSize: 1024
load_features: False
local_rank: 0
max_dataset_size: inf
model: pix2pixHD
multisepcific_dir: ./demo_file/multispecific
nThreads: 2
n_blocks_global: 6
n_blocks_local: 3
n_clusters: 10
n_downsample_E: 4
n_downsample_global: 3
n_local_enhancers: 1
name: people
nef: 16
netG: global
ngf: 64
niter_fix_global: 0
no_flip: False
no_instance: False
no_simswaplogo: False
norm: batch
norm_G: spectralspadesyncbatch3x3
ntest: inf
onnx: None
output_nc: 3
output_path: ./output/test.mp4
phase: test
pic_a_path: ./demo_file/Iron_man.jpg
pic_b_path: ./crop_224/zrf.jpg
pic_specific_path: ./crop_224/zrf.jpg
resize_or_crop: scale_width
results_dir: ./results/
semantic_nc: 3
serial_batches: False
temp_path: ./temp_results
tf_log: False
use_dropout: False
use_encoded_image: False
use_mask: True
verbose: False
video_path: ./demo_file/multi_people.mp4
which_epoch: latest
-------------- End ----------------
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 58, in <module>
    app = Face_detect_crop(name='antelope', root='./insightface_func/models')
  File "C:\Users\User\Desktop\SimSwap-main\insightface_func\face_detect_crop_single.py", line 47, in __init__
    assert 'detection' in self.models
AssertionError

(simswap) C:\Users\User\Desktop\SimSwap-main>

**Comment by PepegaCoding** [comment]
I guess that you didn't download [the relative files](https://onedrive.live.com/?authkey=%21ADJ0aAOSsc90neY&cid=4A83B6B633B029CC&id=4A83B6B633B029CC%215837&parId=4A83B6B633B029CC%215834&action=locate) from [preparation](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md). You need to download and unzip them to ./insightface_func/models

**Comment by Scout12138** [comment]
If you have already downloaded these files, probably you place them in the wrong way. You need to unzip the whole 'antelope.zip' file and not try to remove the '.onnx' files out of 'antelope.

**Comment by gg22mm** [comment]
> 如果您已经下载了这些文件，可能是您将它们放置在错误的位置。您需要解压缩整个“antelope.zip”文件，而不是试图从“antelope”中删除“.onnx”文件。

主要是少了： detection 模型

**Comment by davidmaz123** [comment]
the antelope link is not working anymore... is there any alternative link for me to download the file?

**Comment by hudaodao699** [comment]
> the antelope link is not working anymore... is there any alternative link for me to download the file?

have u got this file? I also need it !! Thx!
