### ISSUE TITLE
couldn't create a writable file...

### ISSUE THREAD

**Issue by oracle9i88** [neuralchen/SimSwap#19]
C:\ProgramData\Miniconda3\envs\simswap\lib\site-packages\torch\serialization.py:658: SourceChangeWarning: source code of class 'torch.nn.parallel.data_parallel.DataParallel' has changed. Tried to save a patch, but couldn't create a writable file DataParallel.patch. Make sure it doesn't exist and your working directory is writable.

**Comment by ftaker887** [comment]
Try to delete the .patch files that are in the same directory as your main python files, then try again.

**Comment by aza0092** [comment]
> Try to delete the .patch files that are in the same directory as your main python files, then try again.

@ExponentialML  where are the .patch files located?
