### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by zndomination** [neuralchen/SimSwap#190]
Hi i been getting the error AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

What do i need to do to fix this?
tried installing cudatoolkit but the error still persist.

thanks

**Comment by Fibonacci134** [comment]
Means you don't have the proper toolkit according to your gpu. Type python and import torch and test to see if cuda is available.
