### ISSUE TITLE
AMP Training

### ISSUE THREAD

**Issue by XWalways** [neuralchen/SimSwap#194]
Hello, while training, if using fp16(```apex ```or ```torch.cuda.amp```), loss=Nan after several iters，any suggestions? Thanks a lot!

**Comment by neuralchen** [comment]
We do not suggest user to employ AMP training or mixing float training, which leads a significant performance degradation.

**Comment by XWalways** [comment]
***@***.***

**Comment by monument-and-sea-all-the-gift** [comment]
rec_loss and id_loss are conflicted，Can you provide me some idea to solve this，thank you

**Comment by neuralchen** [comment]
training scripts are available now!

**Comment by XWalways** [comment]
***@***.***
