### ISSUE TITLE
Average inference time poll (Not an issue) 
Firstly just want to thank the devs for their hard work. You guys are awesome! Please don't abandon this project, it has tons of untapped potential.

### ISSUE THREAD

**Issue by Fibonacci134** [neuralchen/SimSwap#195]
Hey guys, there seems to be a lot of debate and inquiry on reducing inference time/gpu usage etc.. I think it would be kind of helpful if we lost our it/s and Cpu/Gpu specs so that we have a reference point. I will start:
CPU: Ryzen 5600
Gpu: Rtx 1650
 Average it/s on a 1280x720 video:
~6.8- 7 it/s

**Comment by cwalt2014** [comment]
I have a Titan RTX and I am only getting like 3 to 4 it/s max. Anything you did to get those results?

**Comment by Fibonacci134** [comment]
Hey, Yes I did change something. I altered the det_size, put my Gpu into performance mode, Made sure that my version of CUDA was compatible with the setup. Basically didn't use anything from the preparation page other than moviepy. All other packages should be different for most people. I cloned my anaconda environment and basically experimented until everything worked well. For example, both onnxruntime-gpu (1.8 and 1.9) work on my set up but there is a almost 1 it/s speed difference between them. Also check the frame rates of your video. I usually use ffmeg to bring them to 25 fps, if they are too high. Avoid using h.265 encoding and keep the container as a MP4 and h.264.

**Comment by cwalt2014** [comment]
Thank you!

**Comment by Fibonacci134** [comment]
Anytime bro.

**Comment by poorfaker** [comment]
> Hey, Yes I did change something. I altered the det_size, put my Gpu into performance mode, Made sure that my version of CUDA was compatible with the setup. Basically didn't use anything from the preparation page other than moviepy. All other packages should be different for most people. I cloned my anaconda environment and basically experimented until everything worked well. For example, both onnxruntime-gpu (1.8 and 1.9) work on my set up but there is a almost 1 it/s speed difference between them. Also check the frame rates of your video. I usually use ffmeg to bring them to 25 fps, if they are too high. Avoid using h.265 encoding and keep the container as a MP4 and h.264.

----------------------
hello are you not including onnxruntime (no -gpu) ? , before last update i got error when iam only install onnxruntime-gpu, not install onnxruntime. what version of insightface in your env ?
iam using T4 and mask function, i got 3-4 it/s before error message show after update. but after that iam only got max 2 it/s, iam check on my dashboard, performance of GPU always stuck at 20%. This my problem almost got me on 3 months.

**Comment by Fibonacci134** [comment]
Hey, seems that your current set up has a version conflict. Do you have a save backup of your old  environment? Or have you deleted everything?. I believe you should start a new issue since this one says (not an issue and might not attract people with similar issues). I can help you with the proper set up, but I would need some information. Such as : operating system, CPU, GPU, cuda and cudnn versions. Is your graphics card t400?
