### ISSUE TITLE
RTX 3000 Problems and conflicting versions.

### ISSUE THREAD

**Issue by NakoloshGoodsby** [neuralchen/SimSwap#197]
I have an RTX 3080 and Windows 11. No matter what I've done the program wont run. I've noticed that many people also seem to be having trouble getting this to work on new cards. I've done multiple clean re-installs of anaconda and keep running into the same few problems referenced in these issues. #196 #176. I've tried following the solutions in #157 but still no effect. Could it be running all these different versions alongside the 3000 series and windows 11 that is causing this?

**Comment by Fibonacci134** [comment]
Whats the log? What error are you getting? Check CUDA version, install latest drivers. Need more information.

**Comment by NakoloshGoodsby** [comment]
Thanks for responding to me.
I cleaned all packages and reinstalled anaconda and simswap. I tried following #157 suggestion of using "conda install pytorch torchvision torchaudio cudatoolkit=11.3" but there was no package found for torchvision or torchaudio using this. I instead went on anaconda.org and downloaded https://anaconda.org/pytorch/torchaudio and https://anaconda.org/pytorch/torchvision.
I then followed the rest of the preparation page up until the optional (option): pip install onnxruntime-gpu. I ran into one of the same errors I ran into last time.

Traceback (most recent call last):
  File "test_video_swapsingle.py", line 42, in <module>
    opt = TestOptions().parse()
  File "D:\SSG\Dll\SimSP\SimSwap-main\options\base_options.py", line 84, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "C:\Users\Monk\anaconda3\envs\simswap\lib\site-packages\torch\cuda\__init__.py", line 311, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by Fibonacci134** [comment]
Ohh torch not having attribute is a very common issue. When I get home, I will post the steps to fix it. Also remember when installing a specific version using pip, it's == instead of a single =. You just need to install Pytorch with cuda enabled. If anything, I have CUDA 11.5  and have used 11.3 packages before.  I might be able to post the yml of my conda environment and you can just load that directly into conda.

**Comment by NakoloshGoodsby** [comment]
Thanks for the help so far. I had to use conda clean all to get rid of some corrupted packages. I removed the simswap environment after that with anaconda navigator and started again. I've followed the normal preparation and used what you suggested "conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch" and then used the lines from the preparation page. 

(option): pip install --ignore-installed imageio
pip install insightface==0.2.1 onnxruntime moviepy

This installation went better. I think that solved my Cuda problem but I ran into what I seem to remember was a simple error that could be fixed by using a different picture as a source.  Any idea? And again thank you for the help so far.

input mean and std: 127.5 127.5
find model: ./insightface_func/models\antelope\glintr100.onnx recognition
find model: ./insightface_func/models\antelope\scrfd_10g_bnkps.onnx detection
set det-size: (640, 640)
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 64, in <module>
    img_a_align_crop, _ = app.get(img_a_whole,crop_size)
TypeError: 'NoneType' object is not iterable

**Comment by NakoloshGoodsby** [comment]
Thanks a lot for your help Fibonacci. The issue is fixed.

**Comment by Fibonacci134** [comment]
No problem brother,  a good way to get rid of the "not iterable" error is to change det_size to 256. Depending on the size of the picture, (640,640) leads to some images not being able to be properly aligned. Good luck, feel free to ask if you need help. I've been messing with this thing for a while and picked up a few things along the way lolll. Cheers 🥂
