### ISSUE TITLE
Simswap 512 (beta version)  rendering

### ISSUE THREAD

**Issue by birolkuyumcu** [neuralchen/SimSwap#198]
with Simswap 512  ( mode ffhq  ) face swap running without error but face not swapped 
and shown as in image

![image](https://user-images.githubusercontent.com/8981828/151138244-ee94f57c-8be9-43da-8e7d-f11fb0b22521.png)

and also  with use_mask  dont change result,  generate similar image

**Comment by Krakatoa2035** [comment]
I have the same problem

**Comment by Krakatoa2035** [comment]
Help please

**Comment by Krakatoa2035** [comment]
Inten i9 rtx 3060 ti

**Comment by Fibonacci134** [comment]
Did you download 79999_iter.pth from preparation and place it in the correct destination? I believe you have made an error getting the dependencies and the folders into their proper location. Or you have altered something in reverse2original.py accidentally. Go through the preparation and confirm that you guys have all the files.

**Comment by birolkuyumcu** [comment]
> 

Yes  these are correct and if not  rises an error something not found...
i dont change anything at "reverse2original.py"

**Comment by Fibonacci134** [comment]
Is this only happening with 512? Because it seems like one of the files is either missing or corrupted. Where did you put the 512 folder?

**Comment by Fibonacci134** [comment]
> SimSwap/checkpoints/512/550000_net_G.pth

Hey, if you can, please take a picture of the exact filepath while inside the folder. It is definitely a small mistake that has been made somewhere. Have you tried removing it and downloading it again? Also what version of Pytorch are you using?

**Comment by birolkuyumcu** [comment]
there is no filepath error 
if so program rises

```
  warnings.warn(msg, SourceChangeWarning)
./checkpoints/512/550000_net_G.pth not exists yet!
...
File "/app/projects/SimSwap/models/base_model.py", line 58, in load_network
    raise('Generator must exist!')
TypeError: exceptions must derive from BaseException
```
i dont think model is corrupt during download . 
downloaded file is zip . if corrupted  we dont extracted file 

remaining  Pytroch version  :  
my version  is 1.10.1 
but  Normal version of model is worked as expected

**Comment by vladosShikos** [comment]
Check #162, it helped me

**Comment by birolkuyumcu** [comment]
@vladosShikos  thanks 

```

opt.crop_size = 512
crop_size = opt.crop_size
```
solves problem it worked
![image](https://user-images.githubusercontent.com/8981828/154902358-6a452f98-44d9-479d-9612-c069e15f840a.png)

**Comment by woctezuma** [comment]
Interesting.

To clarify for people who are confused about this issue: this happens in Colab notebook if you edit an official one such as [this one](https://colab.research.google.com/github/neuralchen/SimSwap/blob/main/SimSwap%20colab.ipynb).
