### ISSUE TITLE
how to make video faceswap

### ISSUE THREAD

**Issue by molo32** [neuralchen/SimSwap#2]
how to make video faceswap as your example

**Comment by neuralchen** [comment]
We are working hard to publish the video script.

**Comment by neuralchen** [comment]
The video scripts have been released.
Please check it in our program!

**Comment by neuralchen** [comment]
Video scripts have been released!

**Comment by woctezuma** [comment]
I don't know if the OneDrive link to `antelope.zip` is permanent, but if it is, then this works:
```bash
!wget --no-check-certificate \
 https://sh23tw.dm.files.1drv.com/y4mmGiIkNVigkSwOKDcV3nwMJulRGhbtHdkheehR5TArc52UjudUYNXAEvKCii2O5LAmzGCGK6IfleocxuDeoKxDZkNzDRSt4ZUlEt8GlSOpCXAFEkBwaZimtWGDRbpIGpb_pz9Nq5jATBQpezBS6G_UtspWTkgrXHHxhviV2nWy8APPx134zOZrUIbkSF6xnsqzs3uZ_SEX_m9Rey0ykpx9w \
 -O antelope.zip

!unzip antelope.zip -d ./insightface_func/models/
 ```

**Comment by AceSix** [comment]
Thanks for your help! We have employed this solution in colab.
