### ISSUE TITLE
I cannot find a face with these images...

### ISSUE THREAD

**Issue by guchengxi1994** [neuralchen/SimSwap#206]
![6](https://user-images.githubusercontent.com/33513462/155489400-782ca97d-0f9c-4ee0-a13b-a89547cc7e55.png)
![0](https://user-images.githubusercontent.com/33513462/155489568-395533c3-f509-4f79-a926-f3d35d1ca889.png)

**Comment by instant-high** [comment]
If possible try a wider crop of the whole head without "cutting hair"

**Comment by guchengxi1994** [comment]
That makes sense. These people are not real, I generated them by StyleGAN.  I am wandering can we change this part with dlib or other face detector?
```python
def get(self, img, crop_size, max_num=0):
        bboxes, kpss = self.det_model.detect(img,
                                             threshold=self.det_thresh,
                                             max_num=max_num,
                                             metric='default')
        if bboxes.shape[0] == 0:
            return None
        # ret = []
        # for i in range(bboxes.shape[0]):
        #     bbox = bboxes[i, 0:4]
        #     det_score = bboxes[i, 4]
        #     kps = None
        #     if kpss is not None:
        #         kps = kpss[i]
        #     M, _ = face_align.estimate_norm(kps, crop_size, mode ='None') 
        #     align_img = cv2.warpAffine(img, M, (crop_size, crop_size), borderValue=0.0)
        # for i in range(bboxes.shape[0]):
        #     kps = None
        #     if kpss is not None:
        #         kps = kpss[i]
        #     M, _ = face_align.estimate_norm(kps, crop_size, mode ='None') 
        #     align_img = cv2.warpAffine(img, M, (crop_size, crop_size), borderValue=0.0)

        det_score = bboxes[..., 4]

        # select the face with the hightest detection score
        best_index = np.argmax(det_score)

        kps = None
        if kpss is not None:
            kps = kpss[best_index]
        M, _ = face_align.estimate_norm(kps, crop_size, mode = self.mode) 
        align_img = cv2.warpAffine(img, M, (crop_size, crop_size), borderValue=0.0)
        
        return [align_img], [M]
```

**Comment by Fibonacci134** [comment]
Hey, this is a simple fix. You need to open testvideo_swapsingle.py, assuming you're face swapping a video file. The det_size which is set to (640,640) change that to (480,480).
This should solve the problem, if not then change to 256. You will get runtime error, so you must silence the runtime logger by adding this line in the same file
 Import onnxruntime

And around line 61
Add the following:

Onnxruntime.set_default_logger_severity(3)

On line 63 change det_size from (640,640) to (256,256).

Let us know if this solves your issue.

**Comment by guchengxi1994** [comment]
@Fibonacci134  That helps, thanks a lot

**Comment by Fibonacci134** [comment]
No problem at all, glad it helped!

**Comment by Bh-Johnny** [comment]
Thanks a lot for the help !
