### ISSUE TITLE
colab no audio for video error

### ISSUE THREAD

**Issue by AK391** [neuralchen/SimSwap#21]
is there a patch for the colab to fix the error when the video has no audio?

**Comment by woctezuma** [comment]
Use one of my notebook for videos with no audio (GIFs).

https://github.com/woctezuma/SimSwap-colab#usage

**Comment by AK391** [comment]
@woctezuma great also were you able to get it running on cpu in colab?

**Comment by woctezuma** [comment]
I did not try on CPU.

**Comment by NNNNAI** [comment]
I have been fixed the bug for video without audio，the file  I have modified is [videoswap.py](https://github.com/neuralchen/SimSwap/blob/main/util/videoswap.py). Make sure you get the newest code and it should be work for both video with audio and video withouts audio. Many thanks!

**Comment by AK391** [comment]
@NNNNAI great thanks also is it possible to do inference on cpu in colab?

**Comment by NNNNAI** [comment]
I have never test it on cpu, but it should be fine to inference on cpu.You can switch the model and input to cpu,e.g: tensor.cpu(),model.cpu().
