### ISSUE TITLE
Few general issues - TensorRT, low GPU usage, and how do I use VGGFace2-HQ with SimSwap?

### ISSUE THREAD

**Issue by SrGrafoasspee** [neuralchen/SimSwap#213]
- Python 3.10.2
- Cuda compilation tools, release 11.3, V11.3.58
- onnxruntime-gpu last update
- insightface - don't know how to check version
- RTX 3060, 6GB
- NVIDIA Driver 511.79

When I run the command to face swap in a video, I get these errors #173

>[W:onnxruntime:Default, tensorrt_execution_provider.h:53 onnxruntime::TensorrtLogger::log]
>[WARNING] D:\a\_work\1\s\cmake\external\onnx-tensorrt\onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
>input mean and std: 127.5 127.

>[W:onnxruntime:Default, tensorrt_execution_provider.h:53 onnxruntime::TensorrtLogger::log]
>[WARNING] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.3 but loaded cuBLAS/cuBLAS LT 11.5.1
>[W:onnxruntime:Default, tensorrt_execution_provider.h:53 onnxruntime::TensorrtLogger::log]
>TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.2.0

------

I don't know if this is the reason but when the anaconda window is stuck on the aforementioned commands my GPU goes up to 100% but then drops to around 10% when the swapping process begins but CPU usage stays high. I barely get 3 it/s. #156

I added --crop_size 512 recently from the [preparation](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md) page and it works great sometimes and not so great the others but that's understandable as it is in beta but then I recently saw [usage](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/usage.md) page and it says
>We trained a beta version of Simswap 512 on [VGGFace2-HQ](https://github.com/NNNNAI/VGGFace2-HQ) and open sourced the model

Am I supposed to use the VGGFace2-HQ with simswap or is it not needed with 512 crop?

**Comment by neuralchen** [comment]
Now, training scripts are available!
