### ISSUE TITLE
[Errno 2] No such file or directory: 'arcface_model/arcface_checkpoint.tar'

### ISSUE THREAD

**Issue by seconddarko** [neuralchen/SimSwap#217]
I get this error when running "test_one_image.py".  I executed the "Preparation" steps without any problems.  I tried "pip install arcface" while in the environment but it seems that "arcface_model" does not get created from this action or any actions of the "Preparation" steps.  Does anyone know the fix?  Here are my PC specs:

OS - Windows 10
CPU - i7-8700K
GPU - RTX 3070 8 GB
RAM - 32 GB  

![Input](https://user-images.githubusercontent.com/102237997/160300333-6a035654-f367-43d4-bc38-142a021deeb6.JPG)
![Errno2 Pic](https://user-images.githubusercontent.com/102237997/160300340-9f2a6d99-dfa6-446f-9d7f-891f7074ee63.JPG)

**Comment by seconddarko** [comment]
Turns out I put the "arcface_model" in the wrong place.

**Comment by FlorianPra** [comment]
I also get this error, in which folder do I have to put "arcface_model" ?
