### ISSUE TITLE
ERROR: mat1 and mat2 shapes cannot be multiplied (1x131072 and 25088x512)

### ISSUE THREAD

**Issue by hemsflame** [neuralchen/SimSwap#222]
I am getting error: mat1 and mat2 shapes cannot be multiplied (1x131072 and 25088x512), I am trying to use the 512 simswap version using the same code issue #162 , still not able to do it. any help would be appreciated.

**Comment by Fibonacci134** [comment]
Hey, your file reversetooriginal.py is where those numbers are coming from. You might have accidentally changed something. Why dont you replace that particular file with a new one and see if the problem persist. If that doesn't fix it, uninstall numpy and reinstall it using conda.
