### ISSUE TITLE
Training dataset error

### ISSUE THREAD

**Issue by netrunner-exe** [neuralchen/SimSwap#224]
Hi! Thank you very much for posting the training code! I have a problem - want to try using the CelebAMask-HQ dataset for training (VGGFace2-HQ is too heavy for me for downloading) I downloaded it, unpacked - but I always get this error. Do I need to do any preparation for this? How to properly prepare a dataset for training? Please provide some manual for dataset preparation or write a comment about this error. 

```
processing Swapping dataset images...
Finished preprocessing the Swapping dataset, total dirs number: 2...
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Traceback (most recent call last):
  File "/content/SimSwap/data/data_loader_Swapping.py", line 27, in preload
    self.src_image1, self.src_image2 = next(self.dataiter)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1176, in _next_data
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 159, in <module>
    train_loader    = GetLoader(opt.dataset,opt.batchSize,8,1234)
  File "/content/SimSwap/data/data_loader_Swapping.py", line 122, in GetLoader
    prefetcher = data_prefetcher(content_data_loader)
  File "/content/SimSwap/data/data_loader_Swapping.py", line 23, in __init__
    self.preload()
  File "/content/SimSwap/data/data_loader_Swapping.py", line 30, in preload
    self.src_image1, self.src_image2 = next(self.dataiter)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1176, in _next_data
    raise StopIteration
StopIteration
```

**Comment by neuralchen** [comment]
You need to implemente a dataloader for Celeba.
The dataloader presented in our provieded dataloader only supports VGGFace-style dataset , in which the images of each identity are placed in the same folder similar to imagenet.
Additionally, you need to redesign the training losses.

**Comment by netrunner-exe** [comment]
T

> You need to implemente a dataloader for Celeba. The dataloader presented in our provieded dataloader only supports VGGFace-style dataset , in which the images of each identity are placed in the same folder similar to imagenet. Additionally, you need to redesign the training losses.

Thanks for the answer.  Is it possible, if using the VGGFace2-HQ dataset, to finetune existing models that have been published, or just train from scratch?

**Comment by neuralchen** [comment]
You can try your idea.
I think there is no need to finetune the existing ckpt.

**Comment by boreas-l** [comment]
> You need to implemente a dataloader for Celeba. The dataloader presented in our provieded dataloader only supports VGGFace-style dataset , in which the images of each identity are placed in the same folder similar to imagenet. Additionally, you need to redesign the training losses.

why need to redesign the training loss if train on the custom dataset or differenct publish dataset? and how to redesign the training loss?  Thanks all!!

**Comment by ftaker887** [comment]
> > You need to implemente a dataloader for Celeba. The dataloader presented in our provieded dataloader only supports VGGFace-style dataset , in which the images of each identity are placed in the same folder similar to imagenet. Additionally, you need to redesign the training losses.
> 
> why need to redesign the training loss if train on the custom dataset or differenct publish dataset? and how to redesign the training loss? Thanks all!!

The training losses were probably designed around the VGGFace dataset, so you have to tweak the parameters to match which dataset you're using. It will probably perform okay without it, but you'll get much better results if you take the time to do it yourself.

**Comment by ftaker887** [comment]
@netrunner-exe I've created a script to convert the file structures for CelebA if you want to give it a try. It doesn't preserve identities, but it will allow you to train by converting the structure.

```python
import os
import shutil

src_path = SOURCE_DIRECTORY_OF_CELEBA_WITHOUT_/_AT_END #example /home/celebapath
dest_path = DESTINATION_DIRECTORY_OF_CELEBA_WITHOUT_/_AT_END #example /home/celebatrain

src_dir = os.listdir(path=src_path)
curr_iter = 0
file_iter = 0
files_per_folder = 30
new_folder_iter = 0
new_file_path = ''"

print("Processing...")

for image_file in src_dir:
	file_iter += 1
	if curr_iter % files_per_folder == 0:
		file_iter = 0
		new_folder_iter += 1
		new_folder_format = "{0:06d}".format(new_folder_iter)
		new_file_path = f"{dest_path}/n{new_folder_format}"
		os.makedirs(new_file_path)
	
	new_dest = f"{new_file_path}/{image_file}"
	shutil.copyfile(f"{src_path}/{image_file}", new_dest)
	
	
	new_file_name = "{0:04d}".format(file_iter) + "_01.jpg"
	renamed_file = f"{new_file_path}/{new_file_name}"
	os.rename(new_dest, renamed_file)
	curr_iter += 1
	
	print(f"Processed file: {curr_iter}", end="\r")
	
	if curr_iter + 1 == len(src_dir):
		print("Done")
		break
```

**Comment by netrunner-exe** [comment]
> @netrunner-exe I've created a script to convert the file structures for CelebA if you want to give it a try. It doesn't preserve identities, but it will allow you to train by converting the structure.
> 
> ```python
> import os
> import shutil
> 
> src_path = SOURCE_DIRECTORY_OF_CELEBA_WITHOUT_/_AT_END #example /home/celebapath
> dest_path = DESTINATION_DIRECTORY_OF_CELEBA_WITHOUT_/_AT_END #example /home/celebatrain
> 
> src_dir = os.listdir(path=src_path)
> curr_iter = 0
> file_iter = 0
> files_per_folder = 30
> new_folder_iter = 0
> new_file_path = ''
> 
> print("Processing...")
> 
> for image_file in src_dir:
> 	file_iter += 1
> 	if curr_iter % files_per_folder == 0:
> 		file_iter = 0
> 		new_folder_iter += 1
> 		new_folder_format = "{0:06d}".format(new_folder_iter)
> 		new_file_path = f"{dest_path}/n{new_folder_format}"
> 		os.makedirs(new_file_path)
> 	
> 	new_dest = f"{new_file_path}/{image_file}"
> 	shutil.copyfile(f"{src_path}/{image_file}", new_dest)
> 	
> 	
> 	new_file_name = "{0:04d}".format(file_iter) + "_01.jpg"
> 	renamed_file = f"{new_file_path}/{new_file_name}"
> 	os.rename(new_dest, renamed_file)
> 	curr_iter += 1
> 	
> 	print(f"Processed file: {curr_iter}", end="\r")
> 	
> 	if curr_iter + 1 == len(src_dir):
> 		print("Done")
> 		break
> ```

@ftaker887  thank you very much for your help!
