### ISSUE TITLE
noob questions for training 

### ISSUE THREAD

**Issue by ozmix** [neuralchen/SimSwap#225]
What would I need to set up and install to begin training?

**Comment by neuralchen** [comment]
Refer to preparation in Readme

**Comment by SerZhyAle** [comment]
probably the readme and preparation have some parts for old and new release? I did try to intall all from 0 on clear machine, but have same errors while training "dataloader.py", line 517, in __next__" 

and I not able to use the old " test_wholeimage_swapsingle.py" with " model = create_model(opt)" and other errors.
I'll try to investigate Python myself, but please concern to review Readme and preparation list for newbies.

**Comment by neuralchen** [comment]
We update the scripts.
