### ISSUE TITLE
Colab Version Train

### ISSUE THREAD

**Issue by nitnuts** [neuralchen/SimSwap#227]
Can someone make colab script for train 256 / 512 ? I see dataset of face is so big. Colab only free 77GB, How we can do that ?
Thanks

**Comment by papipulato** [comment]
yeah man, its so big for me too, because im using server only 80GB free space. i think we need req separate that faceset.

**Comment by neuralchen** [comment]
Don't worry guys, i am preparing the 256*256 VGGFace2 dataset for users with limited resources.
Be happy with our simswap!

**Comment by neuralchen** [comment]
Colab training scripts are available now!
Please try it!
