### ISSUE TITLE
pretrained model?

### ISSUE THREAD

**Issue by jinfagang** [neuralchen/SimSwap#23]
```
FileNotFoundError: [Errno 2] No such file or directory: 'models/BEST_checkpoint.tar'
```

**Comment by NNNNAI** [comment]
This means you have not specified the --Arc_path argument, you should specify this argument with the path where you place the arcface checkpoint. You can follow the gudience from  [Inference for image or video face swapping](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/usage.md), which have given the example command line. Many thanks.

**Comment by NNNNAI** [comment]
BTW , make sure you have followed the [preparation](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md) to get the environment and pretrained model ready. Many thanks~.
