### ISSUE TITLE
Old test video multi error.

### ISSUE THREAD

**Issue by papipulato** [neuralchen/SimSwap#231]
After update, i got this error
`./checkpoints/people/9900000_net_G.pth not exists yet!
Traceback (most recent call last):
  File "/home/SimSwap/test_video_swapmulti.py", line 55, in <module>
    model = create_model(opt)
  File "/home/SimSwap/models/models.py", line 18, in create_model
    model.initialize(opt)
  File "/home/SimSwap/models/fs_model.py", line 74, in initialize
    self.load_network(self.netG, 'G', opt.which_epoch, pretrained_path)
  File "/home/SimSwap/models/base_model.py", line 71, in load_network
    raise('Generator must exist!')
TypeError: exceptions must derive from BaseException`

**Comment by netrunner-exe** [comment]
> After update, i got this error `./checkpoints/people/9900000_net_G.pth not exists yet! Traceback (most recent call last): File "/home/SimSwap/test_video_swapmulti.py", line 55, in <module> model = create_model(opt) File "/home/SimSwap/models/models.py", line 18, in create_model model.initialize(opt) File "/home/SimSwap/models/fs_model.py", line 74, in initialize self.load_network(self.netG, 'G', opt.which_epoch, pretrained_path) File "/home/SimSwap/models/base_model.py", line 71, in load_network raise('Generator must exist!') TypeError: exceptions must derive from BaseException`

Please read this post to fix your problem #226

**Comment by neuralchen** [comment]
fixed
