### ISSUE TITLE
Some green and purple artifacts during training

### ISSUE THREAD

**Issue by netrunner-exe** [neuralchen/SimSwap#236]
In some faces persist green and purple artifacts during training. Is this normal behavior during training?
![step_1r200](https://user-images.githubusercontent.com/81887288/164622716-cb4d932b-528e-444a-b697-f726001b8df8.jpg)
![step_14rr00](https://user-images.githubusercontent.com/81887288/164622759-3caece4d-26d1-4216-8c55-f7c10be4f896.jpg)
![step_1tt4rr00](https://user-images.githubusercontent.com/81887288/164622799-21d20ba4-371b-4149-8c1d-c5b5dc9c3c0f.jpg)
![step_1600](https://user-images.githubusercontent.com/81887288/164622810-9920d91c-7f53-4af9-8759-f9039b867f12.jpg)
![step_16f00](https://user-images.githubusercontent.com/81887288/164622823-6b019d3d-325a-4e13-b71c-2ecf5a9e521d.jpg)
?

**Comment by Fibonacci134** [comment]
Seems like a masking issue, or dilation of source. Haven't used the training script as of yet so not sure.

**Comment by ozmix** [comment]
I started using the scripts how many iterations have you done so far?. I started it and I'm getting on 6000 so far and it's getting a lot better honestly it should improve as the iterations continue.
