### ISSUE TITLE
Got this error after installing the other pip installs for training code

### ISSUE THREAD

**Issue by ozmix** [neuralchen/SimSwap#240]
------------ Options -------------
Arc_path: arcface_model/arcface_checkpoint.tar
Gdeep: False
batchSize: 4
beta1: 0.0
checkpoints_dir: ./checkpoints
continue_train: False
dataset: /content/TrainingData/vggface2_crop_arcfacealign_224
gpu_ids: 0
isTrain: True
lambda_feat: 10.0
lambda_id: 30.0
lambda_rec: 10.0
load_pretrain: ./checkpoints/simswap224_test
log_frep: 200
lr: 0.0004
model_freq: 10000
name: simswap224_test
niter: 10000
niter_decay: 10000
phase: train
sample_freq: 1000
total_step: 1000000
use_tensorboard: False
which_epoch: 10000
-------------- End ----------------
GPU used :  0
F:\anaconda\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.parallel.data_parallel.DataParallel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
F:\anaconda\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
F:\anaconda\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
F:\anaconda\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.activation.PReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
F:\anaconda\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.MaxPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
F:\anaconda\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
F:\anaconda\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.AdaptiveAvgPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
F:\anaconda\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
F:\anaconda\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.activation.Sigmoid' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
F:\anaconda\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
F:\anaconda\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
processing Swapping dataset images...
Finished preprocessing the Swapping dataset, total dirs number: 0...
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    train_loader    = GetLoader(opt.dataset,opt.batchSize,8,1234)
  File "F:\SS\SimSwap-main\data\data_loader_Swapping.py", line 119, in GetLoader
    drop_last=True,shuffle=True,num_workers=num_workers,pin_memory=True)
  File "F:\anaconda\envs\simswap\lib\site-packages\torch\utils\data\dataloader.py", line 266, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "F:\anaconda\envs\simswap\lib\site-packages\torch\utils\data\sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

(simswap) F:\SS\SimSwap-main>

not sure what I'm supposed to do or if something needs to be added or updated idk how I got this far.

**Comment by netrunner-exe** [comment]
You need to make sure that you correctly specified the path to the unpacked dataset.  Judging by the log, you did not specify it.  For example, extract the dataset to the SimSwap-Main folder so that the vggface2_crop_arcfacealign_224 folder is in it.  The path must be in the format --dataset "./vggface2_crop_arcfacealign_224".

**Comment by ozmix** [comment]
python train.py --name simswap224_test --batchSize 4 --gpu_ids 0 --dataset /content/TrainingData/vggface2_crop_arcfacealign_224 --Gdeep False

**Comment by netrunner-exe** [comment]
> 

Change /content/TrainingData/vggface2_crop_arcfacealign_224 to your path - where the dataset is unzipped.

**Comment by ozmix** [comment]
i d

> > 
> 
> Change /content/TrainingData/vggface2_crop_arcfacealign_224 to your path - where the dataset is unzipped.

i fixed mate but not that way

**Comment by ozmix** [comment]
I solved these issues it turns out it was a few things. 

Firstly i needed unzip the vggface2 file and specify the location like netrunner-exe said 

secondly, I needed to fix the line of code and add a full stop to where the files were located.

Before
python train.py --name simswap224_test --batchSize 4 --gpu_ids 0 --dataset /content/TrainingData/vggface2_crop_arcfacealign_224 --Gdeep Fals

After
python train.py --name simswap224_test --batchSize 4 --gpu_ids 0 --dataset ./content/TrainingData/vggface2_crop_arcfacealign_224 --Gdeep Fals

and now it works for me the training

**Comment by ozmix** [comment]
also thank you netrunner-exe i wouldn't have been able to even do this without cheers bro
