### ISSUE TITLE
Few questions about recent updates

### ISSUE THREAD

**Issue by ftaker887** [neuralchen/SimSwap#244]
Hello @neuralchen , glad to see you're still updating this project. I do have some questions that I would like to ask regarding some of the newer updates.

1. You've stated that the new training algorithm with projection leads to better results. Will you be able to provide the newly trained model in place of the one released last year?
2. Is there a difference between the 512 beta and training VGGFace2-HQ? Is it ideal to train with the dataset or will there be little difference?
3. In the inference section of the README, there's a text description about stating "Stronger feature". Is this a typo, or an indication that there is a new feature allowing for retaining details of the source face?
4. Will SimSwap++ be an entirely new repository with entirely new code, or an addition to this current repository?

Thanks!

**Comment by neuralchen** [comment]
Thank you for your interest in our code repository！
The SimSwap-512 denotes simswap model trained with VGGFace2-HQ, the released model is a beta model which suffers some performance issues.
We had fixed some of those problem.
Training a large model like SimSwap-512 is known to be a resource-intensive task.
We don't have enough resources to fine-tune it.
Our resources are primarily focused on new paper research.
We actually encourage qualified users to further develop this model. 
This model still has a lot of points worth exploring, such as model architecture, discriminator architecture, etc.
SimSwap++ is a entirely new model, which main foucus on model compression.

**Comment by ftaker887** [comment]
> Thank you for your interest in our code repository！ The SimSwap-512 denotes simswap model trained with VGGFace2-HQ, the released model is a beta model which suffers some performance issues. We had fixed some of those problem. Training a large model like SimSwap-512 is known to be a resource-intensive task. We don't have enough resources to fine-tune it. Our resources are primarily focused on new paper research. We actually encourage qualified users to further develop this model. This model still has a lot of points worth exploring, such as model architecture, discriminator architecture, etc, which potentially forms a new papers! SimSwap++ is a entirely new model, which main foucus on model compression.
> 
> We show some results from new SimSwap-512 model:
> 
> ![id_06--attr_2130429-1216_tom_cruise_genes_ckp_780000](https://user-images.githubusercontent.com/18433587/165218438-5226915a-3253-4430-99d8-e6fbb36104ec.png)
> 
> ![id_06--attr_audrey-hepburn-63115_960_720_ckp_780000](https://user-images.githubusercontent.com/18433587/165218579-0d3fd9ea-e942-4143-abc7-29eeb55161d9.png)
> 
> ![id_dlrb2--attr_lyf2_ckp_780000](https://user-images.githubusercontent.com/18433587/165218589-1e845f30-f169-44e6-8489-a0750fa06d82.png)

Thanks for the response, and I appreciate your efforts. I won't ask for the 512 model as I know there are probably implications that may impact your decision to do so. Looking forward to your future work!
