### ISSUE TITLE
Multi GPU Training not working

### ISSUE THREAD

**Issue by mittalgovind** [neuralchen/SimSwap#249]
The `train.py` script does not seem to be able to use multiple GPUs when provided, even after explicitly setting `CUDA_VISIBLE_DEVICES=0,1`. I believe it was not implemented as there is no use of `torchrun`?

**Comment by neuralchen** [comment]
The training scripts contains no multigpu function.
We recommend you refer to the Stylegan v2 or v3 to modify this repo.
Do not employ the Data Parallel "nn.DataParallel" module, as it will greatly increase the overhead of the 0-th GPU.
Use "torch.distributed" instead.

**Comment by mittalgovind** [comment]
Will do. Thanks for the quick response.

**Comment by BeaverInGreenland** [comment]
@mittalgovind could you modify the repo for the Multi GPU training ?
