### ISSUE TITLE
dataloader detail—same identity and different identity?

### ISSUE THREAD

**Issue by boreas-l** [neuralchen/SimSwap#258]
Thankyou for your nice contribution!!  
I am new in Face swap. After read your pape and code, I had some problems，I need some help, Thanks!  
First, in your pape, you said "train one batch for image pairs with the same identity and another
batch for image pairs with different identities alternately" in **Implementation Detail**.  
But in **data_loader_Swapping.py**, return images by **getitem** all from the same dir_tmp，and just different random index?
``` 
def __getitem__(self, index):  
        """Return two src domain images and two dst domain images."""   
        dir_tmp1        = self.dataset[index]  
        dir_tmp1_len    = len(dir_tmp1)  
        filename1   = dir_tmp1[random.randint(0,dir_tmp1_len-1)]  
        filename2   = dir_tmp1[random.randint(0,dir_tmp1_len-1)]  
        image1      = self.img_transform(Image.open(filename1))  
        image2      = self.img_transform(Image.open(filename2))  
        return image1, image2`
```
so if is this, how to implement change same identity and different identity by batch?  
I don't understood this...

**Comment by Noixas** [comment]
Did you get any answer about this?
