### ISSUE TITLE
Dose blur code to img_mask is useless if use_mask=True?

### ISSUE THREAD

**Issue by wikiwen** [neuralchen/SimSwap#274]
As face_mask from face parsing model is enough if use_mask=True. Dose img_mask with blurred square boundary is useless?
So, is it better to remove blurr code to img_mask?
code position:
https://github.com/neuralchen/SimSwap/blob/dd1ecdd2a718636d33977ab3097a69a0ecf080d8/util/reverse2original.py#L129-L141

**Comment by Fibonacci134** [comment]
kernel = np.ones((40,40),np.uint8) 

#This is Area of your rectangular mask , which is  H,W
         img_mask = cv2.erode(img_mask,kernel,iterations = 1) 

# Erosion is used to blend and feather out the of the foreground object, it's like sanding down the top image to blend it with the bottom image in a stack. This is the opposite of dilation which you can also test on the code and play around with
         kernel_size = (20, 20) # Size of aforementioned kernel

            blur_size = tuple(2*i+1 for i in kernel_size) # 
         img_mask = cv2.GaussianBlur(img_mask, blur_size, 0) # Gaussian blur is applied to an image  to get rid of border abruptness, basically so you dont see harsh lines or edges where the 2 images differ. 

So, can you remove the mask? Sure . However; this is a commonly applied technique in face swapping used to  blend images together. You can always play around with the parameters and add other things into the code. You can use PIL ImageEnhance  to adjust sharpness/color of the mask or image to further play with the final image and see what appeals to you.

**Comment by wikiwen** [comment]
> 

Thanks for your reply. I try to remove blurred code for img_mask, then I found a black dotted line on the square boundary.
