### ISSUE TITLE
Memory problem 

### ISSUE THREAD

**Issue by machinbidule62** [neuralchen/SimSwap#300]
Hello everyone
I can’t find the solution every time it fails at 95%. I tried two different video ≈ 8-10 min

Thx for your help.

(simswap) C:\Users\Max\Desktop\SimSwap\SimSwap-main>python test_video_swap_multispecific.py --no_simswaplogo --crop_size 512 --gpu_ids 0 --use_mask  --name people --Arc_path arcface_model/arcface_checkpoint.tar --video_path ./video/video.mp4 --output_path ./output/video.mp4 --temp_path ./temp_results --multisepcific_dir ./video/multispecific

Arc_path: arcface_model/arcface_checkpoint.tar
aspect_ratio: 1.0
batchSize: 8
checkpoints_dir: ./checkpoints
cluster_path: features_clustered_010.npy
crop_size: 512
data_type: 32
dataroot: ./datasets/cityscapes/
display_winsize: 512
engine: None
export_onnx: None
feat_num: 3
fineSize: 512
fp16: False
gpu_ids: [0]
how_many: 50
id_thres: 0.03
image_size: 224
input_nc: 3
instance_feat: False
isTrain: False
label_feat: False
label_nc: 0
latent_size: 512
loadSize: 1024
load_features: False
local_rank: 0
max_dataset_size: inf
model: pix2pixHD
multisepcific_dir: ./video/multispecific
nThreads: 2
n_blocks_global: 6
n_blocks_local: 3
n_clusters: 10
n_downsample_E: 4
n_downsample_global: 3
n_local_enhancers: 1
name: people
nef: 16
netG: global
ngf: 64
niter_fix_global: 0
no_flip: False
no_instance: False
no_simswaplogo: True
norm: batch
norm_G: spectralspadesyncbatch3x3
ntest: inf
onnx: None
output_nc: 3
output_path: ./output/video.mp4
phase: test
pic_a_path: ./crop_224/gdg.jpg
pic_b_path: ./crop_224/zrf.jpg
pic_specific_path: ./crop_224/zrf.jpg
resize_or_crop: scale_width
results_dir: ./results/
semantic_nc: 3
serial_batches: False
temp_path: ./temp_results
tf_log: False
use_dropout: False
use_encoded_image: False
use_mask: True
verbose: False
video_path: ./video/video.mp4
which_epoch: latest
-------------- End ----------------
input mean and std: 127.5 127.5
find model: ./insightface_func/models\antelope\glintr100.onnx recognition
find model: ./insightface_func/models\antelope\scrfd_10g_bnkps.onnx detection
set det-size: (640, 640)
(142, 366, 4)
 95%|██████████████████████████████████████████████████████████████████████▍   | 10906/11457 [1:47:21<05:25,  1.69it/s]
Traceback (most recent call last):
  File "test_video_swap_multispecific.py", line 98, in <module>
    model, app, opt.output_path,temp_results_dir=opt.temp_path,no_simswaplogo=opt.no_simswaplogo,use_mask=opt.use_mask,crop_size=crop_size)
  File "C:\Users\Max\Desktop\SimSwap\SimSwap-main\util\videoswap_multispecific.py", line 114, in video_swap
    os.path.join(temp_results_dir, 'frame_{:0>7d}.jpg'.format(frame_index)),no_simswaplogo,pasring_model =net,use_mask=use_mask, norm = spNorm)
  File "C:\Users\Max\Desktop\SimSwap\SimSwap-main\util\reverse2original.py", line 170, in reverse2wholeimage
    img = img_mask * target_image + (1-img_mask) * img
numpy.core._exceptions.MemoryError: Unable to allocate 21.1 MiB for an array with shape (720, 1280, 3) and data type float64

**Comment by machinbidule62** [comment]
i have gtx 1060 6go... :/

**Comment by machinbidule62** [comment]
I've no problem with small videos.

Sorry for my bad language i'm french

**Comment by monument-and-sea-all-the-gift** [comment]
> I've no problem with small videos.
> 
> Sorry for my bad language i'm french

i can't understand what you say about small videos

**Comment by machinbidule62** [comment]
> > I've no problem with small videos.
> > Sorry for my bad language i'm french
> 
> i can't understand what you say about small videos

Video ~1-2 min

**Comment by jo32111** [comment]
Increase the swap file in windows

**Comment by machinbidule62** [comment]
I will try
