### ISSUE TITLE
Need help in understanding how the models work

### ISSUE THREAD

**Issue by fuzzyfazzy** [neuralchen/SimSwap#304]
Hello, could someone explain how the use of models work? I.e what would happen if the model set only used photos of the target rather than random photos on the Internet? Am just curious over how the model is used when performing the face transfer? I suppose my additional question is what does the training actually do? Because if everyone is training on the same data set then why wouldn't the training models be available for everyone to download or am I missing something here?

**Comment by ExponentialML** [comment]
The model works by getting a bunch of faces, regardless of where the pictures came from, and learns to project the **features** of the faces into latent space. In the code, you'll see this called latent id. You could train on one face, but the amount of compute time necessary, as well as images makes it's better to train on a variety of faces, not just one.

The reason why people are using the same dataset is that it's hard to find one with as much variation as vggface2. We could train it on something like CelebHQ, but it would mostly learn frontal faced images, and a lot of variation is needed.

All models are available for download.

**Comment by fuzzyfazzy** [comment]
Hello! Thanks for the brilliant consise response! It makes sense now. Thankyou.
