### ISSUE TITLE
num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by 1YasserAmmar1** [neuralchen/SimSwap#309]
if yo had another problem that tell you 
**num_samples should be a positive integer value, but got num_samples=0**

...................
**thin just change the train start code by add the batchsize value  --batchSize 4**
.............

`!python train.py --name simswap224_test --batchSize 4 --gpu_ids 0 --dataset ./content/TrainingData/vggface2_crop_arcfacealign_224 --Gdeep Fals`

_Originally posted by @1YasserAmmar1 in https://github.com/neuralchen/SimSwap/issues/307#issuecomment-1200092061_

**Comment by wuXiuSen** [comment]
when i use this
!python train.py --name simswap224_test --batchSize 4 --gpu_ids 0 --dataset ./content/TrainingData/vggface2_crop_arcfacealign_224 --Gdeep Fals

failure , help me
