### ISSUE TITLE
Error in Colab Notebook.

### ISSUE THREAD

**Issue by ericstheguy** [neuralchen/SimSwap#35]
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
<ipython-input-12-19bdee05b3f8> in <module>()
     13 
     14 torch.nn.Module.dump_patches = True
---> 15 model = create_model(opt)
     16 model.eval()
     17 

3 frames
/usr/local/lib/python3.7/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    775             "functionality.")
    776 
--> 777     magic_number = pickle_module.load(f, **pickle_load_args)
    778     if magic_number != MAGIC_NUMBER:
    779         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '<'.

---------------------------------------------------------------------------
How would this be fixed?

**Comment by AceSix** [comment]
Hello. This should be caused by failed downloading due to the google drive cool down. We have now added a github release which will hopefully bypass this problem. You can check our latest updated Colab.

**Comment by ericstheguy** [comment]
Thanks for the detailed response.
