### ISSUE TITLE
AttributeError: 'SGD' object has no attribute 'defaults'

### ISSUE THREAD

**Issue by r3dzone81** [neuralchen/SimSwap#353]

**Comment by r3dzone81** [comment]
I can't run this script in phyton miniconda. IHave Rtx3080 all installed and configured in ambient variable.

**Comment by r3dzone81** [comment]
Also installed conda last version and cuDNN. Nvidia last driver.

**Comment by woctezuma** [comment]
Related:
- https://github.com/neuralchen/SimSwap/issues/355
- https://github.com/neuralchen/SimSwap/issues/354
- https://github.com/neuralchen/SimSwap/issues/353
- https://github.com/neuralchen/SimSwap/issues/180#issuecomment-1341568782
