### ISSUE TITLE
 'SGD' object has no attribute 'defaults 

### ISSUE THREAD

**Issue by zaksmak922** [neuralchen/SimSwap#355]
I can no longer use simswap it gives me this error ------>  'SGD' object has no attribute 'defaults

**Comment by Loc-VD** [comment]
I believe that is because of the Torch version got updated.
Try to add the older version
```!pip install torch==1.12.0```
and run the inference again

**Comment by zaksmak922** [comment]
can you explain to me how to do it? thank you friend

**Comment by acousticdragon** [comment]
crea una linea de texto al principio del proyecto que diga:
!pip install torch==1.12.0

Luego ejecuta el cuaderno normalmente.
Pos: Gracias por la solucion Loc-VD

**Comment by zaksmak922** [comment]
thank you it's working....thanks to : Loc-VD and acousticdragon

**Comment by zaksmak922** [comment]
thank you it's working....thanks to : Loc-VD and acousticdragon
