### ISSUE TITLE
TypeError: __array__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by thelordlugo** [neuralchen/SimSwap#37]
<img width="1103" alt="Screen Shot 2021-07-04 at 1 49 53 PM" src="https://user-images.githubusercontent.com/20141834/124395163-91103980-dcd0-11eb-98c1-c4ddbf2d70f4.png">

**Comment by ftaker887** [comment]
Can you post the script that you were using as well as the commands?

**Comment by thelordlugo** [comment]
> Can you post the script that you were using as well as the commands?

it works on my pc but. when i run it in an nvidia docker container i get that error, here is the code

`
import signal
import time
import os
import cv2
import torch
import fractions
import numpy as np
from PIL import Image
import torch.nn.functional as F
from torchvision import transforms
from models.models import create_model
from options.test_options import TestOptions
from insightface_func.face_detect_crop_mutil import Face_detect_crop
from util.videoswap import video_swap
from util.add_watermark import watermark_image

test = "test"


def test():


    transformer = transforms.Compose([
        transforms.ToTensor(),
        #transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    transformer_Arcface = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    detransformer = transforms.Compose([
        transforms.Normalize([0, 0, 0], [1/0.229, 1/0.224, 1/0.225]),
        transforms.Normalize([-0.485, -0.456, -0.406], [1, 1, 1])
    ])

    opt = TestOptions()
    opt.initialize()
    opt.parser.add_argument('-f') ## dummy arg to avoid bug
    opt = opt.parse()
    opt.pic_a_path = './images/' + (test) + '.png' ## or replace it with image from your own google drive
    opt.video_path = './videos/' + (test) + '.mp4' ## or replace it with video from your own google drive
    opt.output_path = './output/' + (test) + '.mp4'
    opt.temp_path = './docs'
    opt.Arc_path = './arcface_checkpoint.tar'
    opt.isTrain = False

    crop_size = 224

    torch.nn.Module.dump_patches = True
    model = create_model(opt)
    model.eval()


    app = Face_detect_crop(name='antelope', root='./insightface_func/models')
    app.prepare(ctx_id= 0, det_thresh=0.6, det_size=(640,640))

    pic_a = opt.pic_a_path
    # img_a = Image.open(pic_a).convert('RGB')
    img_a_whole = cv2.imread(pic_a)
    img_a_align_crop, _ = app.get(img_a_whole,crop_size)
    img_a_align_crop_pil = Image.fromarray(cv2.cvtColor(img_a_align_crop[0],cv2.COLOR_BGR2RGB)) 
    img_a = transformer_Arcface(img_a_align_crop_pil)
    img_id = img_a.view(-1, img_a.shape[0], img_a.shape[1], img_a.shape[2])

    # convert numpy to tensor
    img_id = img_id.cuda()

    #create latent id
    img_id_downsample = F.interpolate(img_id, scale_factor=0.5)
    latend_id = model.netArc(img_id_downsample)
    latend_id = latend_id.detach().to('cpu')
    latend_id = latend_id/np.linalg.norm(latend_id,axis=1,keepdims=True)
    latend_id = latend_id.to('cuda')

    video_swap(opt.video_path, latend_id, model, app, opt.output_path,temp_results_dir=opt.temp_path)

 

if __name__ == '__main__':
    test()
    
`

**Comment by ftaker887** [comment]
Your error seems to be here:

`img_a_align_crop_pil = Image.fromarray(cv2.cvtColor(img_a_align_crop[0],cv2.COLOR_BGR2RGB)) `

I would try to: Make sure you set up your environment _exactly_ like [this](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md). It seems to me that for whatever reason it's converting that argument into two. Either your Nvidia Docker is setup incorrectly, or you're passing in more than one image as the first parameter when you run the script.

**Comment by thelordlugo** [comment]
Dude you're a genius, i had to downgrade these to the versions you specified 
torch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 insightface==0.2.1
