### ISSUE TITLE
File "test_video_swapsingle.py", line 10, in <module>     import cv2 ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by LukitaG** [neuralchen/SimSwap#390]
![Captura de pantalla 2023-03-23 044728](https://user-images.githubusercontent.com/128665820/227097969-3f1c0b19-3b3e-43ad-9712-11660c2635a7.jpg)

Just trying to understand why this is happening and looking for a solution, anyone else having this problem?
I would appreciate some help guys, Im new with this

**Comment by GingerGeorg** [comment]
Hi, how did you fix this ? Have same problem there. For non-programist it's really tough to fix...

**Comment by LindiaC** [comment]
cv2's name when installing is opencv-python
run `pip install opencv-python` first
