### ISSUE TITLE
Size of dataset?

### ISSUE THREAD

**Issue by Danyache** [neuralchen/SimSwap#4]
Hi!
The work is incredible! But I'm interested in the dataset -- what is the number of images that you trained on? And how much did it take in terms of time (and on which GPUs)?
Another question is if you know where to take this dataset, because as for now it is not available using the direct link https://www.robots.ox.ac.uk/~vgg/data/vgg_face2

**Comment by NNNNAI** [comment]
Sorry for the late reply. By removing some low-resolution images, we probably used nearly 1 million images as the training set. The entire training process may take 2 to 4 days depending on the GPU you are using. Regarding the data set, it seems that this data set cannot be downloaded at present, we downloaded it a long time ago, or can you find if there is a third-party website that has this data set? Many thanks ~

**Comment by Danyache** [comment]
Ok, thank you for answer!

Last question on this topic -- in paper you mention that you removed images "with size smaller than 250 × 250", but does it mean that you've removed all images there the smallest shape is smaller than 250 (for example: image 240x300 you remove) or does it mean that you remove images smaller of total size (so shape[0]*shape[1] < 250^2 -- you remove)?

**Comment by NNNNAI** [comment]
My approach is like this: if shape[0]<250 or shape[1]<250: remove. What you said (so shape[0]*shape[1] <250^2 - you remove) should be fine. As long as you can remove too small pictures.

**Comment by Danyache** [comment]
Ok, thank you!

**Comment by ftaker887** [comment]
> Another question is if you know where to take this dataset, because as for now it is not available using the direct link https://www.robots.ox.ac.uk/~vgg/data/vgg_face2

I remember this question and thought I would swing by. You can download the dataset here via torrent:

https://academictorrents.com/details/535113b8395832f09121bc53ac85d7bc8ef6fa5b

All the best.
