### ISSUE TITLE
colab link stoped wokring

### ISSUE THREAD

**Issue by phill-98** [neuralchen/SimSwap#425]
hey i have being the colab link and it's stop working it's only giving green masks instead of the face any ideas what's going on ? anyone else having this issues any help would be great thanks

thinks i have try 

refreshing the colab 
different gpu settings
testing different vids/pics

**Comment by TransAmMan** [comment]
Same as issue #424. This is happending to me also. Only three complaints. We may be the only people using this Demo. I wish I could find the non-demo program, to see if it is working, and to start using on a regular basis.
