### ISSUE TITLE
Strange Output

### ISSUE THREAD

**Issue by superbunny38** [neuralchen/SimSwap#439]
Hello, thank you for sharing your work :)

I was trying to inference with your model using your given images and video, and the converted video seems very strange. I followed every code in colab, but the result shows as follows:

<img width="1025" alt="image" src="https://github.com/neuralchen/SimSwap/assets/48243487/48f9ae55-1978-46e8-ad83-e526300eb097">

Also, I doubt if this line of warning is a clue for my problem: `Pretrained network G has fewer layers; The following are not initialized:
['down0', 'first_layer', 'last_layer', 'up0']`

I'll wait for your reply, thank you! :)

**Comment by Passion-Leon** [comment]
I solved that. The first test file lack a  hyperparameters. Just add the --crop_size 224/512 after py command. Such as
python test_one_image.py --crop_size 224  --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path crop_224/6.jpg --pic_b_path crop_224/ds.jpg --output_path output/
@superbunny38

**Comment by superbunny38** [comment]
Oh! thank you so much :D
