### ISSUE TITLE
New Issue about：Pretrained network G has fewer layers

### ISSUE THREAD

**Issue by Xiujian-LIANG** [neuralchen/SimSwap#441]
Totally follow the guidance of this method. And I am sure that the pretrain models are downloaded from the link given by SimSwap. 
But the Error is：
Pretrained network G has fewer layers; The following are not initialized:
['down0', 'first_layer', 'last_layer', 'up0']
I see that many same issues here, looking forward to your reply. Thanks.

**Comment by Xiujian-LIANG** [comment]
I solved that. The first test file lack a hyperparameters. Just add the --crop_size 224/512 after py command. Such as
python test_one_image.py --crop_size 224 --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path crop_224/6.jpg --pic_b_path crop_224/ds.jpg --output_path output/

**Comment by LiangqinRen** [comment]
I'm also confused about this, and your post works! Many many thanks.
