### ISSUE TITLE
antelope.zip link not work anymore

### ISSUE THREAD

**Issue by davidmaz123** [neuralchen/SimSwap#474]
Can anyone provide a new link for downloading the zip file? the old link is not working anymore so that I cannot finish the preparation step.

**Comment by davidmaz123** [comment]
solved.

https://drive.google.com/file/d/1goH5lO8BAhTpRhpBeXqWEcGkxiiLlgx9/view

**Comment by woctezuma** [comment]
Related:
- https://github.com/neuralchen/SimSwap/issues/479
- https://github.com/neuralchen/SimSwap/issues/477#issuecomment-2547691671

**Comment by woctezuma** [comment]
I have mirrored the archive content at https://github.com/woctezuma/SimSwap-colab/issues/21.
