### ISSUE TITLE
arcface_checkpoint.tar  Corrupted, decompression failed

### ISSUE THREAD

**Issue by zgsDream** [neuralchen/SimSwap#48]
The arcface_checkpoint.tar downloaded from Google Drive failed to decompressed after being verified by Win and Linux.

Excuse me, is the file damaged?

**Comment by NNNNAI** [comment]
Hi,there. You do not need to unzip the file. As we mentioned in [Preparation](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md), you just need to ***Copy*** the arcface_checkpoint.tar into ./arcface_model.

**Comment by zgsDream** [comment]
Thanks, I didn't read the Copy carefully when I saw "Unzip checkpoints.zip, place it in the root dir./".
