### ISSUE TITLE
audio not working on apple devices

### ISSUE THREAD

**Issue by GianniGi** [neuralchen/SimSwap#49]
Hello, I've sent some videos to a couple of friends, and none of them could listen to the audio (iphones and macbooks), there was no audio at all.

I had no problem listening to them on android or on windows.

Replacing the audio from the output file using ffmepg solved the problem.

**Comment by NNNNAI** [comment]
I see, could you let me know what kind of command line did you use to generate video? Multi Specific or swapping all face in the video?

**Comment by NNNNAI** [comment]
I have tested the demo output of multi specific on both iphone 11 and macbook pro 2020 ,but the audio is fine.

**Comment by GianniGi** [comment]
Thanks for the feedback. I've sent the files to your mail, taken from the whatsapp chat.

I've swapped all the faces in colab, is it possible that whatsapp does some transcoding to the files?

**Comment by NNNNAI** [comment]
I see, I notice the bug. When I download the file in the macbook, there are no aduio.  But there are audio in the macbook when I send the video to my friends(who use macbook) through Wechat. I will fix the bug these day.

**Comment by NNNNAI** [comment]
The problem should be solved now. Please make sure you download the lateset code or run it on colab. Many thanks~.

**Comment by GianniGi** [comment]
Thanks to you for this fantastic tool

Il lun 19 lug 2021, 18:16 Naiyuan Liu ***@***.***> ha scritto:

**Comment by NNNNAI** [comment]
You are welcome~.
