### ISSUE TITLE
Normalization during training

### ISSUE THREAD

**Issue by olegkhomenko** [neuralchen/SimSwap#50]
Hey guys! thank you for the amazing paper! 
While trying to implement a training script for the model I got the following question:
**What type of input and output normalization did you use?** Am I correct that it was `[0..1]` for the input image, and `tanh ([-1..1])` as output? What was the input for the Discriminator: `[-1..1]` or `[0..1]`?

I will be grateful for the answer.

**Comment by NNNNAI** [comment]
Sorry for the late respond~. You are correct for the iinput normalization .The input for D is the out of the G(tanh([-1,1])).Have a nice day.

**Comment by olegkhomenko** [comment]
Thanks!
