### ISSUE TITLE
python: can't open file 'test_video_swapsingle.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by SeaCowTamer** [neuralchen/SimSwap#52]
python: can't open file 'test_video_swapsingle.py': [Errno 2] No such file or directory
how to fix

**Comment by woctezuma** [comment]
`cd SimSwap/`

**Comment by SeaCowTamer** [comment]
i always forget to do that

**Comment by WannabeTechGuy** [comment]
> ```shell
> %cd SimSwap/
> ```

Hello - same issue here "can't open file 'test_video_swapmulti.py': [Errno 2] No such file or directory" 

The first thing that I did within anaconda was change the directory to the SimSwap folder on my desktop (in my case) using "cd C:\Users\Comp\Desktop\SimSwap". Yet when I run the usage command I get the the error. I double checked my file paths as well. Can anyone help?

Thank you

**Comment by woctezuma** [comment]
If you are in the right repository, then the script should be found.
