### ISSUE TITLE
The picture normalization of training and test is different？

### ISSUE THREAD

**Issue by alan525** [neuralchen/SimSwap#55]
I noticed that in the training process, the loaded data were normalized, but in the test process, the attribute image was not normalized.

e.g. in /data/CelebA_class.py both img_id and img_att are  normalized by transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])

in test_one_image.py only img_id normalized. What should I do if I want to fintune the model.

**Comment by NNNNAI** [comment]
The /data/CelebA_class.py is not used during training process. If you want to finetune the model, you just need to follow the normalization in testing process to build a dataset.

**Comment by mobassir94** [comment]
@NNNNAI @alan525 can you kindly tell me which line of code needs to be changed from training pipeline so that the normalization process becomes exactly same as test normalization? Thanks in advance
