### ISSUE TITLE
ERROR: test_video_swapspecific.py

### ISSUE THREAD

**Issue by instant-high** [neuralchen/SimSwap#63]
Since _test_video_swapsingle_ is working perfect, first attempt to swap specific face gives following error (after processing a few frames):

Traceback (most recent call last):
  File "test_video_swapspecific.py", line 83, in <module>
    model, app, opt.output_path,temp_results_dir=opt.temp_path,no_simswaplogo=opt.no_simswaplogo,use_mask=opt.use_mask)
  File "C:\Tutorial\SimSwap\util\videoswap_specific.py", line 98, in video_swap
    os.path.join(temp_results_dir, 'frame_{:0>7d}.jpg'.format(frame_index)),no_simswaplogo,pasring_model =net,use_mask= use_mask, norm = spNorm)
  File "C:\Tutorial\SimSwap\util\reverse2original.py", line 88, in reverse2wholeimage
    for swaped_img, mat ,source_img in zip(swaped_imgs, mats,b_align_crop_tenor_list):
TypeError: zip argument #1 must support iteration

**Comment by woctezuma** [comment]
The problem is that you cannot iterate over `swaped_imgs` for some reason here.

**Comment by NNNNAI** [comment]
Did you test on your own video?

**Comment by instant-high** [comment]
No. I used the mulri people video and the specific image from demo files so far.
Looks like every specific image gives a different number of frames before the error occurs.
But, none of them was swapped... (I opened the images in the temp result folder)

**Comment by NNNNAI** [comment]
I use the demo command line for test_video_swapspecific.py : 
```
python test_video_swapspecific.py --use_mask --pic_specific_path ./demo_file/specific1.png --isTrain false  --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path ./demo_file/Iron_man.jpg --video_path ./demo_file/multi_people_1080p.mp4 --output_path ./output/multi_test_specific.mp4 --temp_path ./temp_results 
```
But it works fine and no error occurs.Did you get the latest version of the code?

**Comment by NNNNAI** [comment]
And all the  images in  the temp result folder  are swapped

**Comment by instant-high** [comment]
I've used the given commandline.

it crashes at the moment the specific image is recognized in the video.

I've cropped the video so it only contains 2 faces but the same... if specific face does not appear in the video it works, but nothing to swap ;-)

I'm not sure to have the latest version... SimSwap code should be up to date.
Were there changes in pytorch or insightface? I did not update that.

Maybe it is a problem with my GPU - 2GB ? 
Got that problem with swapsingle at the beginning, (the old version) you remember?

**Comment by instant-high** [comment]
It runs OK to this point:

_video_path: ./demo_file/crop.mp4
which_epoch: latest
-------------- End ----------------
input mean and std: 127.5 127.5
find model: ./insightface_func/models\antelope\glintr100.onnx recognition
find model: ./insightface_func/models\antelope\scrfd_10g_bnkps.onnx detection
set det-size: (640, 640)
(142, 366, 4)
  0%|                                                  | 0/594 [00:00<?, ?it/s]
Traceback (most recent call last):_

**Comment by NNNNAI** [comment]
Could you provide the full Traceback  report?

**Comment by instant-high** [comment]
C:\Tutorial\SimSwap>python test_video_swapspecific.py --use_mask --pic_specific_path ./demo_file/specific1.png --isTrain false  --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path ./demo_file/Iron_man.jpg --video_path ./demo_file/crop.mp4 --output_path ./output/multi_test_specific.mp4 --temp_path ./temp_results
------------ Options -------------
Arc_path: arcface_model/arcface_checkpoint.tar
aspect_ratio: 1.0
batchSize: 8
checkpoints_dir: ./checkpoints
cluster_path: features_clustered_010.npy
cut_in: 0
data_type: 32
dataroot: ./datasets/cityscapes/
det_thresh: 0.6
detsize: 640
display_winsize: 512
duration: inf
engine: None
export_onnx: None
feat_num: 3
fineSize: 512
first_frame: 0
fp16: False
gpu_ids: [0]
how_many: 50
id_thres: 0.03
image_size: 224
input_nc: 3
instance_feat: False
isTrain: False
kernel_h: 40
kernel_w: 40
label_feat: False
label_nc: 0
latent_size: 512
loadSize: 1024
load_features: False
local_rank: 0
max_dataset_size: inf
model: pix2pixHD
multisepcific_dir: ./demo_file/multispecific
nThreads: 2
n_blocks_global: 6
n_blocks_local: 3
n_clusters: 10
n_downsample_E: 4
n_downsample_global: 3
n_local_enhancers: 1
name: people
nef: 16
netG: global
ngf: 64
niter_fix_global: 0
no_flip: False
no_instance: False
no_simswaplogo: False
norm: batch
norm_G: spectralspadesyncbatch3x3
ntest: inf
onnx: None
output_nc: 3
output_path: ./output/multi_test_specific.mp4
phase: test
pic_a_path: ./demo_file/Iron_man.jpg
pic_b_path: ./crop_224/zrf.jpg
pic_specific_path: ./demo_file/specific1.png
resize_or_crop: scale_width
results_dir: ./results/
semantic_nc: 3
serial_batches: False
temp_path: ./temp_results
tf_log: False
use_dropout: False
use_encoded_image: False
use_mask: True
verbose: False
video_path: ./demo_file/crop.mp4
which_epoch: latest
-------------- End ----------------
input mean and std: 127.5 127.5
find model: ./insightface_func/models\antelope\glintr100.onnx recognition
find model: ./insightface_func/models\antelope\scrfd_10g_bnkps.onnx detection
set det-size: (640, 640)
(142, 366, 4)
  0%|                                                                                                                                                                                     | 0/594 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test_video_swapspecific.py", line 83, in <module>
    model, app, opt.output_path,temp_results_dir=opt.temp_path,no_simswaplogo=opt.no_simswaplogo,use_mask=opt.use_mask)
  File "C:\Tutorial\SimSwap\util\videoswap_specific.py", line 98, in video_swap
    os.path.join(temp_results_dir, 'frame_{:0>7d}.jpg'.format(frame_index)),no_simswaplogo,pasring_model =net,use_mask= use_mask, norm = spNorm)
  File "C:\Tutorial\SimSwap\util\reverse2original.py", line 90, in reverse2wholeimage
    for swaped_img, mat ,source_img in zip(swaped_imgs, mats,b_align_crop_tenor_list):
TypeError: zip argument #1 must support iteration

**Comment by instant-high** [comment]
I'm so sorry....
Now it seems to be working as expected.

I've added some extra parameters to reverse2original.py - reversing to the original file now ->
looks like I did something wrong, it works perfect for single swap but causes the error to specific swap.

So it's my mistake.

**Comment by NNNNAI** [comment]
Never mind. Have a nice day~.
