### ISSUE TITLE
Error when using Face swap for video preset

### ISSUE THREAD

**Issue by MarineBirch723** [neuralchen/SimSwap#66]
<img width="437" alt="Annotation 2021-07-24 140241" src="https://user-images.githubusercontent.com/87900491/126867838-f8635b20-0b79-452d-9a57-e2e4c3ffe063.png">

input mean and std: 127.5 127.5
find model: ./insightface_func/models\antelope\glintr100.onnx recognition
find model: ./insightface_func/models\antelope\scrfd_10g_bnkps.onnx detection
set det-size: (640, 640)
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 50, in <module>
    img_a_align_crop, _ = app.get(img_a_whole,crop_size)
TypeError: 'NoneType' object is not iterable

**Comment by MarineBirch723** [comment]
Solved, picture was invalid

**Comment by woctezuma** [comment]
Yep. #39, #44, #46
