### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by alexlnkp** [neuralchen/SimSwap#70]
When i launch a program it gives me this:

> Arc_path: arcface_model/arcface_checkpoint.tar
> aspect_ratio: 1.0
> batchSize: 8
> checkpoints_dir: ./checkpoints
> cluster_path: features_clustered_010.npy
> data_type: 32
> dataroot: ./datasets/cityscapes/
> display_winsize: 512
> engine: None
> export_onnx: None
> feat_num: 3
> fineSize: 512
> fp16: False
> gpu_ids: [0]
> how_many: 50
> id_thres: 0.03
> image_size: 224
> input_nc: 3
> instance_feat: False
> isTrain: False
> label_feat: False
> label_nc: 0
> latent_size: 512
> loadSize: 1024
> load_features: False
> local_rank: 0
> max_dataset_size: inf
> model: pix2pixHD
> multisepcific_dir: ./demo_file/multispecific
> nThreads: 2
> n_blocks_global: 6
> n_blocks_local: 3
> n_clusters: 10
> n_downsample_E: 4
> n_downsample_global: 3
> n_local_enhancers: 1
> name: people
> nef: 16
> netG: global
> ngf: 64
> niter_fix_global: 0
> no_flip: False
> no_instance: False
> no_simswaplogo: False
> norm: batch
> norm_G: spectralspadesyncbatch3x3
> ntest: inf
> onnx: None
> output_nc: 3
> output_path: ./output/pexels-polina-tankilevitch_swapsingle.mp4
> phase: test
> pic_a_path: ./demo_file/pexels-andrea-piacquadio.jpg
> pic_b_path: ./crop_224/zrf.jpg
> pic_specific_path: ./crop_224/zrf.jpg
> resize_or_crop: scale_width
> results_dir: ./results/
> semantic_nc: 3
> serial_batches: False
> temp_path: ./temp_results
> tf_log: False
> use_dropout: False
> use_encoded_image: False
> use_mask: False
> verbose: False
> video_path: ./demo_file/pexels-polina-tankilevitch.mp4
> which_epoch: latest
> -------------- End ----------------
> input mean and std: 127.5 127.5
> find model: ./insightface_func/models\antelope\glintr100.onnx recognition
> find model: ./insightface_func/models\antelope\scrfd_10g_bnkps.onnx detection
> set det-size: (640, 640)
> Traceback (most recent call last):
>   File "test_video_swapsingle.py", line 51, in <module>
>     img_a_align_crop, _ = app.get(img_a_whole,crop_size)
> TypeError: 'NoneType' object is not iterable

Command i use:
`D:\SimSwap-main>python test_video_swapsingle.py --isTrain false  --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path ./demo_file/pexels-andrea-piacquadio.jpg --video_path ./demo_file/pexels-polina-tankilevitch.mp4 --output_path ./output/pexels-polina-tankilevitch_swapsingle.mp4 --temp_path ./temp_results`

**Comment by alexlnkp** [comment]
It turns out that this message means that it couldn't find a face on and image, using other images works.

**Comment by woctezuma** [comment]
Correct.

#39, #44, #46, #53, #66, #67
