### ISSUE TITLE
Scripts never start，just a blinking cursor. 

### ISSUE THREAD

**Issue by AragakiSaro** [neuralchen/SimSwap#71]
When I get to the last step to actually create the video, I paste the code in and hit enter. The code runs and it gets to where it says ----end---  and then it never starts building the video. No errors. Just a blinking cursor. Any ideas what I'm missing here? Everything else seemed to go smoothly. 

rtx3060 laptop，i check task manager find it didnt work when running but the cpu worked fine with single core.

**Comment by xdmcqaz** [comment]
You just have to wait, it might take 1 hour long depends on your video. Not sure is a bug tho.

**Comment by LMaster321** [comment]
Same thing here. It worked before when I ran in on CPU. Got myself a 3060ti now and it's not working. Tryed reinstalling, not helping
![image](https://user-images.githubusercontent.com/36295005/130320525-5b9acf27-1af7-4b0f-b688-14b90376ee93.png)

**Comment by realies** [comment]
```
conda install cudatoolkit=11.1 -c pytorch -c nvidia
```
fixes it

**Comment by st4tus** [comment]
> kit=11.1 -c pytorch -c nvidia

```
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=11.1
```

**Comment by realies** [comment]
@st4tus, I've updated the command. Check this PR for working instructions - https://github.com/neuralchen/SimSwap/pull/122/files

**Comment by AragakiSaro** [comment]
> @st4tus, I've updated the command. Check this PR for working instructions - https://github.com/neuralchen/SimSwap/pull/122/files

It works, thanks a lot！
