### ISSUE TITLE
Time to release training code?

### ISSUE THREAD

**Issue by nttstar** [neuralchen/SimSwap#8]
Can you give me a rough time? Like within 1 week or 1 month, etc.
Thanks a lot!

**Comment by NNNNAI** [comment]
Thank you for your attention to our work~. We are currently busy with the rebuttal of iccv. Next, we will open source the video face-changing script and training script, and it will probably take no more than a month. : )

**Comment by nttstar** [comment]
@NNNNAI Many thanks for your quick response!

**Comment by BbChip0103** [comment]
any progress/issue of it?
