### ISSUE TITLE
啥时候放训练代码呀~

### ISSUE THREAD

**Issue by MichaelFan01** [neuralchen/SimSwap#81]
如题，训练代码啥时候放出来呀，都期待了好久了

**Comment by LZY2006** [comment]
你确定这个开发者是华人?

**Comment by MichaelFan01** [comment]
> 你确定这个开发者是华人?

上交的啊，你都不看paper么兄弟😂

**Comment by NNNNAI** [comment]
最近在实习，比较少时间维护这个仓库了，不出意外8月底应该能开源训练吧。

**Comment by MichaelFan01** [comment]
> 最近在实习，比较少时间维护这个仓库了，不出意外8月底应该能开源训练吧。

好的，期待

**Comment by MichaelFan01** [comment]
> 最近在实习，比较少时间维护这个仓库了，不出意外8月底应该能开源训练吧。

快到月底了，期待~~~~

**Comment by MichaelFan01** [comment]
> 最近在实习，比较少时间维护这个仓库了，不出意外8月底应该能开源训练吧。

大佬，八月底开源训练代码还有希望么~

**Comment by GeJiuZhe** [comment]
已经九月初了

**Comment by QingXIA233** [comment]
看到不止我一个人在等训练代码我就放心了，边搓手手边坐等

**Comment by MichaelFan01** [comment]
> 看到不止我一个人在等训练代码我就放心了，边搓手手边坐等

哈哈哈，前排有瓜子，边嗑边等

**Comment by MichaelFan01** [comment]
大佬，是不是最近在赶AAAI, AAAI过后能放训练代码么~~~

**Comment by QingXIA233** [comment]
> 大佬，是不是最近在赶AAAI, AAAI过后能放训练代码么~~~

我觉得以你的能力完全可以复现训练代码，能蹲一波你的么

**Comment by ykk648** [comment]
> > 大佬，是不是最近在赶AAAI, AAAI过后能放训练代码么~~~
> 
> 我觉得以你的能力完全可以复现训练代码，能蹲一波你的么

我觉得以你的能力完全可以复现训练代码，能蹲一波你的么

**Comment by MichaelFan01** [comment]
> 我觉得以你的能力完全可以复现训练代码，能蹲一波你的么

我觉得以你的能力完全可以复现训练代码，能蹲一波你的么

**Comment by ykk648** [comment]
> > 我觉得以你的能力完全可以复现训练代码，能蹲一波你的么
> 
> 我觉得以你的能力完全可以复现训练代码，能蹲一波你的么

不能，复现了也是公司财产 :(

**Comment by QingXIA233** [comment]
我在b站催up主更新都没这么积极orz

**Comment by MichaelFan01** [comment]
> 我在b站催up主更新都没这么积极orz

继续等待

**Comment by ykk648** [comment]
try https://github.com/a312863063/SimSwap-train

**Comment by neuralchen** [comment]
Training scripts are available now!
