### ISSUE TITLE
AssertionError!!HELP!!!!

### ISSUE THREAD

**Issue by Aurora-Rong** [neuralchen/SimSwap#84]
python test_video_swapsingle.py --isTrain false --use_mask --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path ./demo_file/Iron_man.jpg --video_path ./demo_file/multi_people_1080p.mp4 --output_path ./output/multi_test_swapsingle.mp4 --temp_path ./temp_results
------------ Options -------------
Arc_path: arcface_model/arcface_checkpoint.tar
aspect_ratio: 1.0
batchSize: 8
checkpoints_dir: ./checkpoints
cluster_path: features_clustered_010.npy
data_type: 32
dataroot: ./datasets/cityscapes/
display_winsize: 512
engine: None
export_onnx: None
feat_num: 3
fineSize: 512
fp16: False
gpu_ids: [0]
how_many: 50
id_thres: 0.03
image_size: 224
input_nc: 3
instance_feat: False
isTrain: False
label_feat: False
label_nc: 0
latent_size: 512
loadSize: 1024
load_features: False
local_rank: 0
max_dataset_size: inf
model: pix2pixHD
multisepcific_dir: ./demo_file/multispecific
nThreads: 2
n_blocks_global: 6
n_blocks_local: 3
n_clusters: 10
n_downsample_E: 4
n_downsample_global: 3
n_local_enhancers: 1
name: people
nef: 16
netG: global
ngf: 64
niter_fix_global: 0
no_flip: False
no_instance: False
no_simswaplogo: False
norm: batch
norm_G: spectralspadesyncbatch3x3
ntest: inf
onnx: None
output_nc: 3
output_path: ./output/multi_test_swapsingle.mp4
phase: test
pic_a_path: ./demo_file/Iron_man.jpg
pic_b_path: ./crop_224/zrf.jpg
pic_specific_path: ./crop_224/zrf.jpg
resize_or_crop: scale_width
results_dir: ./results/
semantic_nc: 3
serial_batches: False
temp_path: ./temp_results
tf_log: False
use_dropout: False
use_encoded_image: False
use_mask: True
verbose: False
video_path: ./demo_file/multi_people_1080p.mp4
which_epoch: latest
-------------- End ----------------
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 44, in <module>
    app = Face_detect_crop(name='antelope', root='./insightface_func/models')
  File "M:\桌面\STAR\SimSwap-main\insightface_func\face_detect_crop_single.py", line 39, in __init__
    assert 'detection' in self.models
AssertionError

__________________________________________________________________________________
老哥，帮我，确实找不到这是个啥错误！！bro！！

**Comment by woctezuma** [comment]
#29

**Comment by NNNNAI** [comment]
看这里的[preparation](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md)

**Comment by Aurora-Rong** [comment]
> #29 
thank you！！why I dont find this

**Comment by Aurora-Rong** [comment]
> 看这里的[preparation](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md)

感谢老哥
