### ISSUE TITLE
Does it fit into the video?能放视频进行训练吗？

### ISSUE THREAD

**Issue by Aurora-Rong** [neuralchen/SimSwap#85]
I found that I can only use a picture to change, can you use video, like deepface, into the video, and then multiple frames to analyze, I found that after the fusion of the face features are not very obvious, there are easy to appear edge contours
发现好像只能使用一张图片去换，能不能使用视频呢，就像deepface那样，放入视频，然后多张帧去分析，我发现融合后的脸特征不是很明显，容易有出现边缘轮廓

**Comment by NNNNAI** [comment]
目前不支持，但我们正在考虑这个方案
