### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by kratadata** [neuralchen/SimSwap#93]
After following the preparation steps and extracting the models in "./insightface_func/models" I am still getting the following error.
Using absolute paths doesn't fix the problem.

`Traceback (most recent call last):
  File "test_video_swapsingle.py", line 44, in <module>
    app = Face_detect_crop(name='antelope', root='./insightface_func/models')
  File "C:\Users\Paulina\SimSwap\insightface_func\face_detect_crop_single.py", line 39, in __init__
    assert 'detection' in self.models
AssertionError`

Here is my directory structure:

![Capture](https://user-images.githubusercontent.com/48999145/129697699-c9cc8a8d-3243-4c88-b32f-39a27c049c6d.PNG)
![Capture2](https://user-images.githubusercontent.com/48999145/129697700-2f19f694-c0d6-437a-a65d-050cf82be265.PNG)

**Comment by kratadata** [comment]
Solved

**Comment by SaroshZDandoti** [comment]
Hello, how did you solve this problem?

**Comment by jiaozn** [comment]
> Solved

i came across same problem...so,how did you fix it?thnx!
