### ISSUE TITLE
CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page, make sure they're in the PATH, and that your GPU is supported.

### ISSUE THREAD

**Issue by Dogchaseacar** [neuralchen/SimSwap#98]
HI thank you for your project!
I just came across this problem. 
I am sure that the CUDA_PATH is correct and my version is 10.2 as you suggested. Also the GPU driver is compatible.
But it just can not work by showing 
CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page, make sure they're in the PATH, and that your GPU is supported.
 I am appreciated for your reply!

**Comment by NNNNAI** [comment]
Try pip uninstall onnxruntime-gpu and then pip install onnxruntime

**Comment by Dogchaseacar** [comment]
@NNNNAI Thanks so much, by updating the CUDA to 11.1, I make it work now!

**Comment by khelgor** [comment]
Hello, i'm totally noob with python, i tried your command line pip uninstall onnxruntime-gpu in python but it say "invalid synthax
